import {
  FOUNDATION_THEME,
  AccordionV2Type,
  type ResponsiveAccordionV2Tokens,
} from '@juspay/blend-design-system'

/**
 * `ACCORDIONV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/AccordionV2/accordionV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.ACCORDIONV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const ACCORDIONV2_TOKENS: ResponsiveAccordionV2Tokens = {
  sm: {
    gap: {
      [AccordionV2Type.BORDER]: FOUNDATION_THEME.unit[0],
      [AccordionV2Type.NO_BORDER]: FOUNDATION_THEME.unit[0],
    },
    borderRadius: {
      [AccordionV2Type.BORDER]: FOUNDATION_THEME.border.radius[8],
      [AccordionV2Type.NO_BORDER]: FOUNDATION_THEME.border.radius[8],
    },
    trigger: {
      content: {
        gap: FOUNDATION_THEME.unit[8],
      },
      backgroundColor: {
        [AccordionV2Type.BORDER]: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          active: FOUNDATION_THEME.colors.gray[50],
          disabled: FOUNDATION_THEME.colors.gray[50],
          open: FOUNDATION_THEME.colors.gray[50],
        },
        [AccordionV2Type.NO_BORDER]: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          active: FOUNDATION_THEME.colors.gray[50],
          disabled: FOUNDATION_THEME.colors.gray[50],
          open: 'transparent',
        },
      },
      border: {
        [AccordionV2Type.BORDER]: {
          default: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          hover: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          active: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          disabled: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          open: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
        },
        [AccordionV2Type.NO_BORDER]: {
          default: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          hover: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          active: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          disabled: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          open: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
        },
      },
      padding: {
        [AccordionV2Type.BORDER]: `${FOUNDATION_THEME.unit[20]} ${FOUNDATION_THEME.unit[16]}`,
        [AccordionV2Type.NO_BORDER]: `${FOUNDATION_THEME.unit[20]} ${FOUNDATION_THEME.unit[16]}`,
      },
      text: {
        gap: FOUNDATION_THEME.unit[4],
        title: {
          fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[600],
          lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          color: {
            default: FOUNDATION_THEME.colors.gray[800],
            hover: FOUNDATION_THEME.colors.gray[800],
            active: FOUNDATION_THEME.colors.gray[800],
            disabled: FOUNDATION_THEME.colors.gray[500],
            open: FOUNDATION_THEME.colors.gray[800],
          },
        },
        subtext: {
          fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[400],
          lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          gap: FOUNDATION_THEME.unit[4],
          color: {
            default: FOUNDATION_THEME.colors.gray[600],
            hover: FOUNDATION_THEME.colors.gray[600],
            active: FOUNDATION_THEME.colors.gray[600],
            disabled: FOUNDATION_THEME.colors.gray[300],
            open: FOUNDATION_THEME.colors.gray[600],
          },
        },
      },
      slot: {
        height: FOUNDATION_THEME.unit[16],
      },
    },
    separator: {
      color: {
        [AccordionV2Type.BORDER]: FOUNDATION_THEME.colors.gray[200],
        [AccordionV2Type.NO_BORDER]: FOUNDATION_THEME.colors.gray[200],
      },
    },
    chevron: {
      height: FOUNDATION_THEME.unit[16],
      color: {
        default: FOUNDATION_THEME.colors.gray[500],
        hover: FOUNDATION_THEME.colors.gray[600],
        active: FOUNDATION_THEME.colors.gray[600],
        disabled: FOUNDATION_THEME.colors.gray[300],
        open: FOUNDATION_THEME.colors.gray[600],
      },
    },
  },
  lg: {
    gap: {
      [AccordionV2Type.BORDER]: FOUNDATION_THEME.unit[24],
      [AccordionV2Type.NO_BORDER]: FOUNDATION_THEME.unit[8],
    },
    borderRadius: {
      [AccordionV2Type.BORDER]: FOUNDATION_THEME.border.radius[8],
      [AccordionV2Type.NO_BORDER]: FOUNDATION_THEME.border.radius[8],
    },
    trigger: {
      content: {
        gap: FOUNDATION_THEME.unit[8],
      },
      backgroundColor: {
        [AccordionV2Type.BORDER]: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          active: FOUNDATION_THEME.colors.gray[50],
          disabled: FOUNDATION_THEME.colors.gray[50],
          open: FOUNDATION_THEME.colors.gray[50],
        },
        [AccordionV2Type.NO_BORDER]: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          active: FOUNDATION_THEME.colors.gray[50],
          disabled: FOUNDATION_THEME.colors.gray[50],
          open: 'transparent',
        },
      },
      border: {
        [AccordionV2Type.BORDER]: {
          default: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          hover: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          active: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          disabled: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
          open: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
        },
        [AccordionV2Type.NO_BORDER]: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
          open: 'none',
        },
      },
      padding: {
        [AccordionV2Type.BORDER]: `${FOUNDATION_THEME.unit[16]} ${FOUNDATION_THEME.unit[16]}`,
        [AccordionV2Type.NO_BORDER]: `${FOUNDATION_THEME.unit[16]} ${FOUNDATION_THEME.unit[12]}`,
      },
      text: {
        gap: FOUNDATION_THEME.unit[4],
        title: {
          fontSize: FOUNDATION_THEME.font.size.body.lg.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[600],
          lineHeight: 16,
          color: {
            default: FOUNDATION_THEME.colors.gray[800],
            hover: FOUNDATION_THEME.colors.gray[800],
            active: FOUNDATION_THEME.colors.gray[800],
            disabled: FOUNDATION_THEME.colors.gray[500],
            open: FOUNDATION_THEME.colors.gray[800],
          },
        },
        subtext: {
          fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[400],
          lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          gap: FOUNDATION_THEME.unit[4],
          color: {
            default: FOUNDATION_THEME.colors.gray[600],
            hover: FOUNDATION_THEME.colors.gray[600],
            active: FOUNDATION_THEME.colors.gray[600],
            disabled: FOUNDATION_THEME.colors.gray[300],
            open: FOUNDATION_THEME.colors.gray[600],
          },
        },
      },
      slot: {
        height: FOUNDATION_THEME.unit[16],
      },
    },
    separator: {
      color: {
        [AccordionV2Type.BORDER]: FOUNDATION_THEME.colors.gray[200],
        [AccordionV2Type.NO_BORDER]: FOUNDATION_THEME.colors.gray[200],
      },
    },
    chevron: {
      height: FOUNDATION_THEME.unit[16],
      color: {
        default: FOUNDATION_THEME.colors.gray[500],
        hover: FOUNDATION_THEME.colors.gray[600],
        active: FOUNDATION_THEME.colors.gray[600],
        disabled: FOUNDATION_THEME.colors.gray[300],
        open: FOUNDATION_THEME.colors.gray[600],
      },
    },
  },
}
