import { FOUNDATION_THEME, type ResponsiveAlertV2Tokens } from '@juspay/blend-design-system'

/**
 * `ALERTV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/AlertV2/alertV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.ALERTV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const ALERTV2_TOKENS: ResponsiveAlertV2Tokens = {
  sm: {
    width: '100%',
    maxWidth: '900px',
    minWidth: '300px',
    border: {
      primary: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
      },
      warning: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.yellow[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.yellow[500]}`,
      },
      success: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.green[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.green[500]}`,
      },
      purple: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
      neutral: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.gray[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.gray[500]}`,
      },
      error: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
      },
      orange: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
      },
    },
    borderRadius: FOUNDATION_THEME.border.radius[8],
    backgroundColor: {
      primary: {
        subtle: FOUNDATION_THEME.colors.primary[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      warning: {
        subtle: FOUNDATION_THEME.colors.yellow[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      success: {
        subtle: FOUNDATION_THEME.colors.green[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      purple: {
        subtle: FOUNDATION_THEME.colors.purple[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      neutral: {
        subtle: FOUNDATION_THEME.colors.gray[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      error: {
        subtle: FOUNDATION_THEME.colors.red[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      orange: {
        subtle: FOUNDATION_THEME.colors.orange[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
    },
    padding: {
      top: FOUNDATION_THEME.unit[16],
      right: FOUNDATION_THEME.unit[16],
      bottom: FOUNDATION_THEME.unit[16],
      left: FOUNDATION_THEME.unit[16],
    },
    gap: {
      right: FOUNDATION_THEME.unit[16],
      bottom: FOUNDATION_THEME.unit[10],
    },
    slot: {
      maxHeight: FOUNDATION_THEME.unit[16],
    },
    mainContainer: {
      gap: FOUNDATION_THEME.unit[8],
      content: {
        gap: {
          right: FOUNDATION_THEME.unit[28],
          bottom: FOUNDATION_THEME.unit[18],
        },
        textContainer: {
          gap: FOUNDATION_THEME.unit[8],
          heading: {
            color: {
              primary: FOUNDATION_THEME.colors.gray[700],
              warning: FOUNDATION_THEME.colors.gray[700],
              success: FOUNDATION_THEME.colors.gray[700],
              purple: FOUNDATION_THEME.colors.gray[700],
              neutral: FOUNDATION_THEME.colors.gray[700],
              error: FOUNDATION_THEME.colors.gray[700],
              orange: FOUNDATION_THEME.colors.gray[700],
            },
            fontWeight: FOUNDATION_THEME.font.weight[600],
            fontSize: FOUNDATION_THEME.font.fontSize[14],
            lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          },
          description: {
            color: {
              primary: FOUNDATION_THEME.colors.gray[600],
              warning: FOUNDATION_THEME.colors.gray[600],
              success: FOUNDATION_THEME.colors.gray[600],
              purple: FOUNDATION_THEME.colors.gray[600],
              neutral: FOUNDATION_THEME.colors.gray[600],
              error: FOUNDATION_THEME.colors.gray[600],
              orange: FOUNDATION_THEME.colors.gray[600],
            },
            fontWeight: FOUNDATION_THEME.font.weight[400],
            fontSize: FOUNDATION_THEME.font.fontSize[14],
            lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          },
        },
        actionContainer: {
          gap: FOUNDATION_THEME.unit[20],
          primaryAction: {
            color: {
              primary: FOUNDATION_THEME.colors.primary[700],
              warning: FOUNDATION_THEME.colors.yellow[700],
              success: FOUNDATION_THEME.colors.green[700],
              purple: FOUNDATION_THEME.colors.purple[700],
              neutral: FOUNDATION_THEME.colors.gray[700],
              error: FOUNDATION_THEME.colors.red[700],
              orange: FOUNDATION_THEME.colors.orange[700],
            },
            fontWeight: FOUNDATION_THEME.font.weight[600],
            fontSize: FOUNDATION_THEME.font.fontSize[14],
            lineHeight: FOUNDATION_THEME.font.lineHeight[20],
          },
          secondaryAction: {
            color: {
              primary: FOUNDATION_THEME.colors.primary[700],
              warning: FOUNDATION_THEME.colors.yellow[700],
              success: FOUNDATION_THEME.colors.green[700],
              purple: FOUNDATION_THEME.colors.purple[700],
              neutral: FOUNDATION_THEME.colors.gray[700],
              error: FOUNDATION_THEME.colors.red[700],
              orange: FOUNDATION_THEME.colors.orange[700],
            },
            fontWeight: FOUNDATION_THEME.font.weight[600],
            fontSize: FOUNDATION_THEME.font.fontSize[14],
            lineHeight: FOUNDATION_THEME.font.lineHeight[20],
          },
        },
      },
      closeButton: {
        color: {
          primary: FOUNDATION_THEME.colors.primary[700],
          warning: FOUNDATION_THEME.colors.yellow[700],
          success: FOUNDATION_THEME.colors.green[700],
          purple: FOUNDATION_THEME.colors.purple[700],
          neutral: FOUNDATION_THEME.colors.gray[700],
          error: FOUNDATION_THEME.colors.red[700],
          orange: FOUNDATION_THEME.colors.orange[700],
        },
        height: FOUNDATION_THEME.unit[16],
        width: FOUNDATION_THEME.unit[16],
      },
    },
  },
  lg: {
    width: '100%',
    maxWidth: '900px',
    minWidth: '300px',
    border: {
      primary: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
      },
      warning: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.yellow[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.yellow[500]}`,
      },
      success: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.green[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.green[500]}`,
      },
      purple: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
      neutral: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.gray[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.gray[500]}`,
      },
      error: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
      },
      orange: {
        subtle: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        noFill: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
      },
    },
    borderRadius: FOUNDATION_THEME.border.radius[8],
    backgroundColor: {
      primary: {
        subtle: FOUNDATION_THEME.colors.primary[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      warning: {
        subtle: FOUNDATION_THEME.colors.yellow[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      success: {
        subtle: FOUNDATION_THEME.colors.green[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      purple: {
        subtle: FOUNDATION_THEME.colors.purple[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      neutral: {
        subtle: FOUNDATION_THEME.colors.gray[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      error: {
        subtle: FOUNDATION_THEME.colors.red[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
      orange: {
        subtle: FOUNDATION_THEME.colors.orange[50],
        noFill: FOUNDATION_THEME.colors.gray[0],
      },
    },
    padding: {
      top: FOUNDATION_THEME.unit[16],
      right: FOUNDATION_THEME.unit[16],
      bottom: FOUNDATION_THEME.unit[16],
      left: FOUNDATION_THEME.unit[16],
    },
    gap: {
      right: FOUNDATION_THEME.unit[16],
      bottom: FOUNDATION_THEME.unit[10],
    },
    slot: {
      maxHeight: FOUNDATION_THEME.unit[16],
    },
    mainContainer: {
      gap: FOUNDATION_THEME.unit[8],
      content: {
        gap: {
          right: FOUNDATION_THEME.unit[28],
          bottom: FOUNDATION_THEME.unit[18],
        },
        textContainer: {
          gap: FOUNDATION_THEME.unit[8],
          heading: {
            color: {
              primary: FOUNDATION_THEME.colors.gray[700],
              warning: FOUNDATION_THEME.colors.gray[700],
              success: FOUNDATION_THEME.colors.gray[700],
              purple: FOUNDATION_THEME.colors.gray[700],
              neutral: FOUNDATION_THEME.colors.gray[700],
              error: FOUNDATION_THEME.colors.gray[700],
              orange: FOUNDATION_THEME.colors.gray[700],
            },
            fontWeight: FOUNDATION_THEME.font.weight[600],
            fontSize: FOUNDATION_THEME.font.fontSize[14],
            lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          },
          description: {
            color: {
              primary: FOUNDATION_THEME.colors.gray[600],
              warning: FOUNDATION_THEME.colors.gray[600],
              success: FOUNDATION_THEME.colors.gray[600],
              purple: FOUNDATION_THEME.colors.gray[600],
              neutral: FOUNDATION_THEME.colors.gray[600],
              error: FOUNDATION_THEME.colors.gray[600],
              orange: FOUNDATION_THEME.colors.gray[600],
            },
            fontWeight: FOUNDATION_THEME.font.weight[400],
            fontSize: FOUNDATION_THEME.font.fontSize[14],
            lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          },
        },
        actionContainer: {
          gap: FOUNDATION_THEME.unit[20],
          primaryAction: {
            color: {
              primary: FOUNDATION_THEME.colors.primary[700],
              warning: FOUNDATION_THEME.colors.yellow[700],
              success: FOUNDATION_THEME.colors.green[700],
              purple: FOUNDATION_THEME.colors.purple[700],
              neutral: FOUNDATION_THEME.colors.gray[700],
              error: FOUNDATION_THEME.colors.red[700],
              orange: FOUNDATION_THEME.colors.orange[700],
            },
            fontWeight: FOUNDATION_THEME.font.weight[600],
            fontSize: FOUNDATION_THEME.font.fontSize[14],
            lineHeight: FOUNDATION_THEME.font.lineHeight[20],
          },
          secondaryAction: {
            color: {
              primary: FOUNDATION_THEME.colors.primary[700],
              warning: FOUNDATION_THEME.colors.yellow[700],
              success: FOUNDATION_THEME.colors.green[700],
              purple: FOUNDATION_THEME.colors.purple[700],
              neutral: FOUNDATION_THEME.colors.gray[700],
              error: FOUNDATION_THEME.colors.red[700],
              orange: FOUNDATION_THEME.colors.orange[700],
            },
            fontWeight: FOUNDATION_THEME.font.weight[600],
            fontSize: FOUNDATION_THEME.font.fontSize[14],
            lineHeight: FOUNDATION_THEME.font.lineHeight[20],
          },
        },
      },
      closeButton: {
        color: {
          primary: FOUNDATION_THEME.colors.primary[700],
          warning: FOUNDATION_THEME.colors.yellow[700],
          success: FOUNDATION_THEME.colors.green[700],
          purple: FOUNDATION_THEME.colors.purple[700],
          neutral: FOUNDATION_THEME.colors.gray[700],
          error: FOUNDATION_THEME.colors.red[700],
          orange: FOUNDATION_THEME.colors.orange[700],
        },
        height: FOUNDATION_THEME.unit[16],
        width: FOUNDATION_THEME.unit[16],
      },
    },
  },
}
