import {
  FOUNDATION_THEME,
  AvatarV2Shape,
  AvatarV2Size,
  AvatarV2Status,
  type ResponsiveAvatarV2Tokens,
} from '@juspay/blend-design-system'

/**
 * `AVATARV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/AvatarV2/avatarV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.AVATARV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const AVATARV2_TOKENS: ResponsiveAvatarV2Tokens = {
  sm: {
    gap: FOUNDATION_THEME.unit[8],
    container: {
      backgroundColor: FOUNDATION_THEME.colors.gray[100],
      width: {
        [AvatarV2Size.SM]: FOUNDATION_THEME.unit[24],
        [AvatarV2Size.REGULAR]: FOUNDATION_THEME.unit[28],
        [AvatarV2Size.MD]: FOUNDATION_THEME.unit[32],
        [AvatarV2Size.LG]: FOUNDATION_THEME.unit[56],
        [AvatarV2Size.XL]: FOUNDATION_THEME.unit[64],
      },
      height: {
        [AvatarV2Size.SM]: FOUNDATION_THEME.unit[24],
        [AvatarV2Size.REGULAR]: FOUNDATION_THEME.unit[28],
        [AvatarV2Size.MD]: FOUNDATION_THEME.unit[32],
        [AvatarV2Size.LG]: FOUNDATION_THEME.unit[56],
        [AvatarV2Size.XL]: FOUNDATION_THEME.unit[64],
      },
      borderRadius: {
        [AvatarV2Shape.CIRCULAR]: FOUNDATION_THEME.border.radius.full,
        [AvatarV2Shape.ROUNDED]: FOUNDATION_THEME.border.radius[8],
      },
      image: {
        border: `1px solid ${FOUNDATION_THEME.colors.gray[0]}`,
      },
      fallbackText: {
        border: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        fontSize: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.font.size.body.xs.fontSize,
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.font.size.body.xs.fontSize,
          [AvatarV2Size.MD]: FOUNDATION_THEME.font.size.body.sm.fontSize,
          [AvatarV2Size.LG]: FOUNDATION_THEME.font.size.heading.md.fontSize,
          [AvatarV2Size.XL]: FOUNDATION_THEME.font.size.heading.lg.fontSize,
        },
        fontWeight: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.font.weight[500],
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.font.weight[500],
          [AvatarV2Size.MD]: FOUNDATION_THEME.font.weight[500],
          [AvatarV2Size.LG]: FOUNDATION_THEME.font.weight[600],
          [AvatarV2Size.XL]: FOUNDATION_THEME.font.weight[600],
        },
        lineHeight: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.font.size.body.xs.lineHeight,
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.font.size.body.xs.lineHeight,
          [AvatarV2Size.MD]: FOUNDATION_THEME.font.size.body.sm.lineHeight,
          [AvatarV2Size.LG]: FOUNDATION_THEME.font.size.heading.md.lineHeight,
          [AvatarV2Size.XL]: FOUNDATION_THEME.font.size.heading.lg.lineHeight,
        },
        color: FOUNDATION_THEME.colors.gray[0],
      },
      status: {
        width: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.unit[8],
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.unit[10],
          [AvatarV2Size.MD]: FOUNDATION_THEME.unit[12],
          [AvatarV2Size.LG]: FOUNDATION_THEME.unit[18],
          [AvatarV2Size.XL]: FOUNDATION_THEME.unit[20],
        },
        height: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.unit[8],
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.unit[10],
          [AvatarV2Size.MD]: FOUNDATION_THEME.unit[12],
          [AvatarV2Size.LG]: FOUNDATION_THEME.unit[18],
          [AvatarV2Size.XL]: FOUNDATION_THEME.unit[20],
        },
        border: {
          [AvatarV2Size.SM]: `${FOUNDATION_THEME.unit[0.5]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
          [AvatarV2Size.REGULAR]: `${FOUNDATION_THEME.unit[1]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
          [AvatarV2Size.MD]: `${FOUNDATION_THEME.unit[1]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
          [AvatarV2Size.LG]: `${FOUNDATION_THEME.unit[2]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
          [AvatarV2Size.XL]: `${FOUNDATION_THEME.unit[2]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
        },
        borderRadius: FOUNDATION_THEME.border.radius.full,
        backgroundColor: {
          [AvatarV2Status.NONE]: 'transparent',
          [AvatarV2Status.ONLINE]: FOUNDATION_THEME.colors.green[500],
          [AvatarV2Status.OFFLINE]: FOUNDATION_THEME.colors.gray[400],
          [AvatarV2Status.AWAY]: FOUNDATION_THEME.colors.yellow[500],
          [AvatarV2Status.BUSY]: FOUNDATION_THEME.colors.red[500],
        },
        boxShadow: '0 0 0 1px rgba(255, 255, 255, 0.8)',
        position: {
          [AvatarV2Shape.CIRCULAR]: {
            [AvatarV2Size.SM]: {
              top: '-2px',
              right: '-2px',
              bottom: '0px',
            },
            [AvatarV2Size.REGULAR]: {
              top: '-3px',
              right: '-3px',
              bottom: '0px',
            },
            [AvatarV2Size.MD]: {
              top: '-3px',
              right: '-4px',
              bottom: '0px',
            },
            [AvatarV2Size.LG]: {
              top: '0.2px',
              right: '-3px',
              bottom: '0px',
            },
            [AvatarV2Size.XL]: {
              top: '1.167px',
              right: '-3px',
              bottom: '0px',
            },
          },
          [AvatarV2Shape.ROUNDED]: {
            [AvatarV2Size.SM]: {
              top: '-2px',
              right: '-3px',
              bottom: '-1px',
            },
            [AvatarV2Size.REGULAR]: {
              top: '-2px',
              right: '-3px',
              bottom: '-1px',
            },
            [AvatarV2Size.MD]: {
              top: '-3.667px',
              right: '-5px',
              bottom: '-3px',
            },
            [AvatarV2Size.LG]: {
              top: '-3.111px',
              right: '-8.222px',
              bottom: '-3px',
            },
            [AvatarV2Size.XL]: {
              top: '-3.111px',
              right: '-10.222px',
              bottom: '-4px',
            },
          },
        },
      },
    },
    slot: {
      height: FOUNDATION_THEME.unit[16],
      width: FOUNDATION_THEME.unit[16],
    },
  },
  lg: {
    gap: FOUNDATION_THEME.unit[12],
    container: {
      backgroundColor: FOUNDATION_THEME.colors.gray[100],
      width: {
        [AvatarV2Size.SM]: FOUNDATION_THEME.unit[24],
        [AvatarV2Size.REGULAR]: FOUNDATION_THEME.unit[32],
        [AvatarV2Size.MD]: FOUNDATION_THEME.unit[40],
        [AvatarV2Size.LG]: FOUNDATION_THEME.unit[80],
        [AvatarV2Size.XL]: FOUNDATION_THEME.unit[144],
      },
      height: {
        [AvatarV2Size.SM]: FOUNDATION_THEME.unit[24],
        [AvatarV2Size.REGULAR]: FOUNDATION_THEME.unit[32],
        [AvatarV2Size.MD]: FOUNDATION_THEME.unit[40],
        [AvatarV2Size.LG]: FOUNDATION_THEME.unit[80],
        [AvatarV2Size.XL]: FOUNDATION_THEME.unit[144],
      },
      borderRadius: {
        [AvatarV2Shape.CIRCULAR]: FOUNDATION_THEME.border.radius.full,
        [AvatarV2Shape.ROUNDED]: FOUNDATION_THEME.border.radius[6],
      },
      image: {
        border: `1px solid ${FOUNDATION_THEME.colors.gray[0]}`,
      },
      fallbackText: {
        border: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        fontSize: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.font.size.body.xs.fontSize,
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.font.size.body.xs.fontSize,
          [AvatarV2Size.MD]: FOUNDATION_THEME.font.size.body.sm.fontSize,
          [AvatarV2Size.LG]: FOUNDATION_THEME.font.size.heading.md.fontSize,
          [AvatarV2Size.XL]: FOUNDATION_THEME.font.size.heading.lg.fontSize,
        },
        fontWeight: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.font.weight[500],
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.font.weight[500],
          [AvatarV2Size.MD]: FOUNDATION_THEME.font.weight[500],
          [AvatarV2Size.LG]: FOUNDATION_THEME.font.weight[600],
          [AvatarV2Size.XL]: FOUNDATION_THEME.font.weight[600],
        },
        lineHeight: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.font.size.body.xs.lineHeight,
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.font.size.body.xs.lineHeight,
          [AvatarV2Size.MD]: FOUNDATION_THEME.font.size.body.sm.lineHeight,
          [AvatarV2Size.LG]: FOUNDATION_THEME.font.size.heading.md.lineHeight,
          [AvatarV2Size.XL]: FOUNDATION_THEME.font.size.heading.lg.lineHeight,
        },
        color: FOUNDATION_THEME.colors.gray[0],
      },
      status: {
        width: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.unit[8],
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.unit[12],
          [AvatarV2Size.MD]: FOUNDATION_THEME.unit[14],
          [AvatarV2Size.LG]: FOUNDATION_THEME.unit[20],
          [AvatarV2Size.XL]: FOUNDATION_THEME.unit[28],
        },
        height: {
          [AvatarV2Size.SM]: FOUNDATION_THEME.unit[8],
          [AvatarV2Size.REGULAR]: FOUNDATION_THEME.unit[12],
          [AvatarV2Size.MD]: FOUNDATION_THEME.unit[14],
          [AvatarV2Size.LG]: FOUNDATION_THEME.unit[20],
          [AvatarV2Size.XL]: FOUNDATION_THEME.unit[28],
        },
        border: {
          [AvatarV2Size.SM]: `${FOUNDATION_THEME.unit[0.5]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
          [AvatarV2Size.REGULAR]: `${FOUNDATION_THEME.unit[1]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
          [AvatarV2Size.MD]: `${FOUNDATION_THEME.unit[1]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
          [AvatarV2Size.LG]: `${FOUNDATION_THEME.unit[2]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
          [AvatarV2Size.XL]: `${FOUNDATION_THEME.unit[2]} solid ${FOUNDATION_THEME.colors.gray[0]}`,
        },
        borderRadius: FOUNDATION_THEME.border.radius.full,
        backgroundColor: {
          [AvatarV2Status.NONE]: 'transparent',
          [AvatarV2Status.ONLINE]: FOUNDATION_THEME.colors.green[500],
          [AvatarV2Status.OFFLINE]: FOUNDATION_THEME.colors.gray[400],
          [AvatarV2Status.AWAY]: FOUNDATION_THEME.colors.yellow[500],
          [AvatarV2Status.BUSY]: FOUNDATION_THEME.colors.red[500],
        },
        boxShadow: '0 0 0 1px rgba(255, 255, 255, 0.8)',
        position: {
          [AvatarV2Shape.CIRCULAR]: {
            [AvatarV2Size.SM]: {
              top: '-2px',
              right: '-2px',
              bottom: '0px',
            },
            [AvatarV2Size.REGULAR]: {
              top: '-3px',
              right: '-3px',
              bottom: '0px',
            },
            [AvatarV2Size.MD]: {
              top: '-3px',
              right: '-3px',
              bottom: '0px',
            },
            [AvatarV2Size.LG]: {
              top: '0px',
              right: '2px',
              bottom: '0px',
            },
            [AvatarV2Size.XL]: {
              top: '8px',
              right: '3px',
              bottom: '0px',
            },
          },
          [AvatarV2Shape.ROUNDED]: {
            [AvatarV2Size.SM]: {
              top: '-3px',
              right: '-3px',
              bottom: '-3px',
            },
            [AvatarV2Size.REGULAR]: {
              top: '-3px',
              right: '-3px',
              bottom: '-3px',
            },
            [AvatarV2Size.MD]: {
              top: '-3px',
              right: '-3px',
              bottom: '-3px',
            },
            [AvatarV2Size.LG]: {
              top: '-5px',
              right: '-5px',
              bottom: '-5px',
            },
            [AvatarV2Size.XL]: {
              top: '-8px',
              right: '-8px',
              bottom: '-8px',
            },
          },
        },
      },
    },
    slot: {
      height: FOUNDATION_THEME.unit[20],
      width: FOUNDATION_THEME.unit[20],
    },
  },
}
