import { FOUNDATION_THEME, type ResponsiveButtonV2Tokens } from '@juspay/blend-design-system'

/**
 * `BUTTONV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/ButtonV2/buttonV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.BUTTONV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const BUTTONV2_TOKENS: ResponsiveButtonV2Tokens = {
  sm: {
    gap: FOUNDATION_THEME.unit[6],
    // Pattern: backgroundColor.[variant].[subType].[state]
    // Example: backgroundColor.primary.default.hover
    backgroundColor: {
      primary: {
        default: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.primary[600]} -5%, ${FOUNDATION_THEME.colors.primary[500]} 107.5%)`,
          hover: FOUNDATION_THEME.colors.primary[600],
          active: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.primary[600]} -5%, ${FOUNDATION_THEME.colors.primary[500]} 107.5%)`,
          disabled: FOUNDATION_THEME.colors.primary[300],
        },
        iconOnly: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.primary[600]} -5%, ${FOUNDATION_THEME.colors.primary[500]} 107.5%)`,
          hover: FOUNDATION_THEME.colors.primary[600],
          active: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.primary[600]} -5%, ${FOUNDATION_THEME.colors.primary[500]} 107.5%)`,
          disabled: FOUNDATION_THEME.colors.primary[300],
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      secondary: {
        default: {
          default: FOUNDATION_THEME.colors.gray[0],
          hover: FOUNDATION_THEME.colors.gray[50],
          active: FOUNDATION_THEME.colors.gray[0],
          disabled: FOUNDATION_THEME.colors.gray[150],
        },
        iconOnly: {
          default: FOUNDATION_THEME.colors.gray[0],
          hover: FOUNDATION_THEME.colors.gray[50],
          active: FOUNDATION_THEME.colors.gray[0],
          disabled: FOUNDATION_THEME.colors.gray[150],
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      danger: {
        default: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.red[600]} 0%, ${FOUNDATION_THEME.colors.red[500]} 93.75%)`,
          hover: FOUNDATION_THEME.colors.red[600],
          active: FOUNDATION_THEME.colors.red[500],
          disabled: FOUNDATION_THEME.colors.red[300],
        },
        iconOnly: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.red[600]} 0%, ${FOUNDATION_THEME.colors.red[500]} 93.75%)`,
          hover: FOUNDATION_THEME.colors.red[600],
          active: FOUNDATION_THEME.colors.red[500],
          disabled: FOUNDATION_THEME.colors.red[300],
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      success: {
        default: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.green[600]} 0%, ${FOUNDATION_THEME.colors.green[500]} 100%)`,
          hover: FOUNDATION_THEME.colors.green[600],
          active: FOUNDATION_THEME.colors.green[600],
          disabled: FOUNDATION_THEME.colors.green[300],
        },
        iconOnly: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.green[600]} 0%, ${FOUNDATION_THEME.colors.green[500]} 100%)`,
          hover: FOUNDATION_THEME.colors.green[600],
          active: FOUNDATION_THEME.colors.green[600],
          disabled: FOUNDATION_THEME.colors.green[300],
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
    },
    borderRadius: {
      sm: {
        primary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        secondary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        danger: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        success: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
      },
      md: {
        primary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        secondary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        danger: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        success: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
      },
      lg: {
        primary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        secondary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        danger: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        success: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
      },
    },
    // Pattern: padding.[direction].[size].[variant].[subType]
    // Example: padding.top.lg.primary.inline
    padding: {
      top: {
        sm: {
          primary: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        md: {
          primary: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        lg: {
          primary: {
            default: '13px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '13px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '13px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '13px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
      },
      right: {
        sm: {
          primary: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        md: {
          primary: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        lg: {
          primary: {
            default: '16px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
      },
      bottom: {
        sm: {
          primary: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        md: {
          primary: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        lg: {
          primary: {
            default: '13px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '13px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '13px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '13px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
      },
      left: {
        sm: {
          primary: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        md: {
          primary: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        lg: {
          primary: {
            default: '16px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '16px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
      },
    },
    // Pattern: border.[variant].[subType].[state]
    // Example: border.danger.default.disabled
    border: {
      primary: {
        default: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.primary[500]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.primary[300]}`,
        },
        iconOnly: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.primary[500]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.primary[300]}`,
        },
        inline: {
          default: `none`,
          hover: `none`,
          active: `none`,
          disabled: `none`,
        },
      },
      secondary: {
        default: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
          active: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          disabled: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
        },
        iconOnly: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
          active: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          disabled: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
        },
        inline: {
          default: `none`,
          hover: `none`,
          active: `none`,
          disabled: `none`,
        },
      },
      danger: {
        default: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.red[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.red[500]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.red[500]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.red[300]}`,
        },
        iconOnly: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.red[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.red[500]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.red[500]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.red[300]}`,
        },
        inline: {
          default: `none`,
          hover: `none`,
          active: `none`,
          disabled: `none`,
        },
      },
      success: {
        default: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.green[500]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.green[300]}`,
        },
        iconOnly: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.green[500]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.green[300]}`,
        },
        inline: {
          default: `none`,
          hover: `none`,
          active: `none`,
          disabled: `none`,
        },
      },
    },
    // Pattern: shadow.[variant].[subType].[state]
    // Example: shadow.primary.default.hover
    shadow: {
      primary: {
        default: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: `0 2px 5px 0 rgba(0, 0, 0, 0.10), 0 3px 4px 0 ${FOUNDATION_THEME.colors.primary[800]} inset`,
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        iconOnly: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: `0 2px 5px 0 rgba(0, 0, 0, 0.10), 0 3px 4px 0 ${FOUNDATION_THEME.colors.primary[800]} inset`,
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      secondary: {
        default: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0px 4px 4px 0px rgba(0, 0, 0, 0.10) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        iconOnly: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      danger: {
        default: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0 2px 3px 0 rgba(0, 0, 0, 0.08), 0 4px 4px 0 rgba(0, 0, 0, 0.12) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        iconOnly: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0 2px 3px 0 rgba(0, 0, 0, 0.08), 0 4px 4px 0 rgba(0, 0, 0, 0.12) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      success: {
        default: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0 2px 3px 0 rgba(0, 0, 0, 0.08), 0 4px 4px 0 rgba(0, 0, 0, 0.12) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        iconOnly: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0 2px 3px 0 rgba(0, 0, 0, 0.08), 0 4px 4px 0 rgba(0, 0, 0, 0.12) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
    },
    // Pattern: outline.[variant].[subType].[state]
    // Example: outline.success.iconOnly.active
    // outline: {
    //     primary: {
    //         default: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.primary[200]}`,
    //             disabled: `none`,
    //         },
    //         iconOnly: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.primary[200]}`,
    //             disabled: `none`,
    //         },
    //         inline: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
    //             disabled: `none`,
    //         },
    //     },
    //     secondary: {
    //         default: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.gray[100]}`,
    //             disabled: `none`,
    //         },
    //         iconOnly: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.gray[100]}`,
    //             disabled: `none`,
    //         },
    //         inline: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.gray[100]}`,
    //             disabled: `none`,
    //         },
    //     },
    //     danger: {
    //         default: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.red[200]}`,
    //             disabled: `none`,
    //         },
    //         iconOnly: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.red[200]}`,
    //             disabled: `none`,
    //         },
    //         inline: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.red[200]}`,
    //             disabled: `none`,
    //         },
    //     },
    //     success: {
    //         default: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.green[200]}`,
    //             disabled: `none`,
    //         },
    //         iconOnly: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.green[200]}`,
    //             disabled: `none`,
    //         },
    //         inline: {
    //             default: `none`,
    //             hover: `none`,
    //             active: `3px solid ${FOUNDATION_THEME.colors.green[200]}`,
    //             disabled: `none`,
    //         },
    //     },
    // },
    text: {
      // Pattern: text.color.[variant].[subType].[state]
      // Example: text.color.primary.inline.hover
      color: {
        primary: {
          default: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          iconOnly: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          inline: {
            default: FOUNDATION_THEME.colors.primary[600],
            hover: FOUNDATION_THEME.colors.primary[600],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.primary[300],
          },
        },
        secondary: {
          default: {
            default: FOUNDATION_THEME.colors.gray[600],
            hover: FOUNDATION_THEME.colors.gray[600],
            active: FOUNDATION_THEME.colors.gray[600],
            disabled: FOUNDATION_THEME.colors.gray[300],
          },
          iconOnly: {
            default: FOUNDATION_THEME.colors.gray[600],
            hover: FOUNDATION_THEME.colors.gray[600],
            active: FOUNDATION_THEME.colors.gray[600],
            disabled: FOUNDATION_THEME.colors.gray[400],
          },
          inline: {
            default: FOUNDATION_THEME.colors.gray[600],
            hover: FOUNDATION_THEME.colors.gray[600],
            active: FOUNDATION_THEME.colors.gray[600],
            disabled: FOUNDATION_THEME.colors.gray[400],
          },
        },
        danger: {
          default: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          iconOnly: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          inline: {
            default: FOUNDATION_THEME.colors.red[600],
            hover: FOUNDATION_THEME.colors.red[600],
            active: FOUNDATION_THEME.colors.red[600],
            disabled: FOUNDATION_THEME.colors.red[400],
          },
        },
        success: {
          default: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          iconOnly: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          inline: {
            default: FOUNDATION_THEME.colors.green[600],
            hover: FOUNDATION_THEME.colors.green[600],
            active: FOUNDATION_THEME.colors.green[600],
            disabled: FOUNDATION_THEME.colors.green[400],
          },
        },
      },
      fontSize: {
        sm: FOUNDATION_THEME.font.fontSize[14],
        md: FOUNDATION_THEME.font.fontSize[14],
        lg: FOUNDATION_THEME.font.fontSize[14],
      },
      fontWeight: {
        sm: FOUNDATION_THEME.font.weight[500],
        md: FOUNDATION_THEME.font.weight[500],
        lg: FOUNDATION_THEME.font.weight[500],
      },
      lineHeight: {
        sm: FOUNDATION_THEME.font.lineHeight[20],
        md: FOUNDATION_THEME.font.lineHeight[20],
        lg: FOUNDATION_THEME.font.lineHeight[20],
      },
    },
  },
  lg: {
    gap: FOUNDATION_THEME.unit[6],
    backgroundColor: {
      primary: {
        default: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.primary[500]} -5%, ${FOUNDATION_THEME.colors.primary[600]} 107.5%)`,
          hover: FOUNDATION_THEME.colors.primary[600],
          active: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.primary[500]} -5%, ${FOUNDATION_THEME.colors.primary[600]} 107.5%)`,
          disabled: FOUNDATION_THEME.colors.primary[300],
        },
        iconOnly: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.primary[500]} -5%, ${FOUNDATION_THEME.colors.primary[600]} 107.5%)`,
          hover: FOUNDATION_THEME.colors.primary[600],
          active: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.primary[500]} -5%, ${FOUNDATION_THEME.colors.primary[600]} 107.5%)`,
          disabled: FOUNDATION_THEME.colors.primary[300],
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      secondary: {
        default: {
          default: FOUNDATION_THEME.colors.gray[0],
          hover: FOUNDATION_THEME.colors.gray[50],
          active: FOUNDATION_THEME.colors.gray[0],
          disabled: FOUNDATION_THEME.colors.gray[150],
        },
        iconOnly: {
          default: FOUNDATION_THEME.colors.gray[0],
          hover: FOUNDATION_THEME.colors.gray[50],
          active: FOUNDATION_THEME.colors.gray[0],
          disabled: FOUNDATION_THEME.colors.gray[150],
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      danger: {
        default: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.red[500]} 0%, ${FOUNDATION_THEME.colors.red[600]} 93.75%)`,
          hover: FOUNDATION_THEME.colors.red[600],
          active: FOUNDATION_THEME.colors.red[500],
          disabled: FOUNDATION_THEME.colors.red[300],
        },
        iconOnly: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.red[500]} 0%, ${FOUNDATION_THEME.colors.red[600]} 93.75%)`,
          hover: FOUNDATION_THEME.colors.red[600],
          active: FOUNDATION_THEME.colors.red[500],
          disabled: FOUNDATION_THEME.colors.red[300],
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      success: {
        default: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.green[500]} 0%, ${FOUNDATION_THEME.colors.green[600]} 100%)`,
          hover: FOUNDATION_THEME.colors.green[600],
          active: FOUNDATION_THEME.colors.green[600],
          disabled: FOUNDATION_THEME.colors.green[300],
        },
        iconOnly: {
          default: `linear-gradient(180deg, ${FOUNDATION_THEME.colors.green[500]} 0%, ${FOUNDATION_THEME.colors.green[600]} 100%)`,
          hover: FOUNDATION_THEME.colors.green[600],
          active: FOUNDATION_THEME.colors.green[600],
          disabled: FOUNDATION_THEME.colors.green[300],
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
    },
    borderRadius: {
      sm: {
        primary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        secondary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        danger: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        success: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
      },
      md: {
        primary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        secondary: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        danger: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        success: {
          default: FOUNDATION_THEME.border.radius[10],
          iconOnly: FOUNDATION_THEME.border.radius[10],
          inline: FOUNDATION_THEME.border.radius[6],
        },
      },
      lg: {
        primary: {
          default: FOUNDATION_THEME.border.radius[12],
          iconOnly: FOUNDATION_THEME.border.radius[12],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        secondary: {
          default: FOUNDATION_THEME.border.radius[12],
          iconOnly: FOUNDATION_THEME.border.radius[12],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        danger: {
          default: FOUNDATION_THEME.border.radius[12],
          iconOnly: FOUNDATION_THEME.border.radius[12],
          inline: FOUNDATION_THEME.border.radius[6],
        },
        success: {
          default: FOUNDATION_THEME.border.radius[12],
          iconOnly: FOUNDATION_THEME.border.radius[12],
          inline: FOUNDATION_THEME.border.radius[6],
        },
      },
    },
    // Pattern: padding.[direction].[size].[variant].[subType]
    // Example: padding.top.lg.primary.inline
    padding: {
      top: {
        sm: {
          primary: {
            default: '4.5px',
            iconOnly: '8.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '4.5px',
            iconOnly: '8.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '4.5px',
            iconOnly: '8.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        md: {
          primary: {
            default: '6.5px',
            iconOnly: '9.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '6.5px',
            iconOnly: '9.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '6.5px',
            iconOnly: '9.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        lg: {
          primary: {
            default: '8.5px',
            iconOnly: '11.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '9px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '8.5px',
            iconOnly: '11.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '8.5px',
            iconOnly: '11.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
      },
      right: {
        sm: {
          primary: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        md: {
          primary: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        lg: {
          primary: {
            default: '16px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
      },
      bottom: {
        sm: {
          primary: {
            default: '4.5px',
            iconOnly: '8.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '5px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '4.5px',
            iconOnly: '8.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '4.5px',
            iconOnly: '8.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        md: {
          primary: {
            default: '6.5px',
            iconOnly: '9.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '7px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '6.5px',
            iconOnly: '9.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '6.5px',
            iconOnly: '9.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        lg: {
          primary: {
            default: '8.5px',
            iconOnly: '11.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '9px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '8.5px',
            iconOnly: '11.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '8.5px',
            iconOnly: '11.5px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
      },
      left: {
        sm: {
          primary: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '9px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        md: {
          primary: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '10px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
        lg: {
          primary: {
            default: '16px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
          secondary: {
            default: '16px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
          danger: {
            default: '16px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
          success: {
            default: '16px',
            iconOnly: '12px',
            inline: FOUNDATION_THEME.unit[0],
          },
        },
      },
    },
    // Pattern: border.[variant].[subType].[state]
    // Example: border.danger.default.disabled
    border: {
      primary: {
        default: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.primary[300]}`,
        },
        iconOnly: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.primary[600]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.primary[300]}`,
        },
        inline: {
          default: `none`,
          hover: `none`,
          active: `none`,
          disabled: `none`,
        },
      },
      secondary: {
        default: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
          active: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          disabled: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
        },
        iconOnly: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
          active: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          disabled: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
        },
        inline: {
          default: `none`,
          hover: `none`,
          active: `none`,
          disabled: `none`,
        },
      },
      danger: {
        default: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.red[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.red[600]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.red[500]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.red[300]}`,
        },
        iconOnly: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.red[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.red[600]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.red[500]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.red[300]}`,
        },
        inline: {
          default: `none`,
          hover: `none`,
          active: `none`,
          disabled: `none`,
        },
      },
      success: {
        default: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.green[300]}`,
        },
        iconOnly: {
          default: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          hover: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          active: `1.5px solid ${FOUNDATION_THEME.colors.green[600]}`,
          disabled: `1.5px solid ${FOUNDATION_THEME.colors.green[300]}`,
        },
        inline: {
          default: `none`,
          hover: `none`,
          active: `none`,
          disabled: `none`,
        },
      },
    },
    // Pattern: shadow.[variant].[subType].[state]
    // Example: shadow.primary.default.hover
    shadow: {
      primary: {
        default: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: `0 2px 5px 0 rgba(0, 0, 0, 0.10), 0 3px 6px 0 ${FOUNDATION_THEME.colors.primary[800]} inset`,
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        iconOnly: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: `0 2px 5px 0 rgba(0, 0, 0, 0.10), 0 3px 4px 0 ${FOUNDATION_THEME.colors.primary[800]} inset`,
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      secondary: {
        default: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0px 4px 4px 0px rgba(0, 0, 0, 0.10) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        iconOnly: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      danger: {
        default: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        iconOnly: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
      success: {
        default: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        iconOnly: {
          default: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          hover: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          active: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
          disabled: '0px 4px 4px 0px rgba(0, 0, 0, 0.15) inset',
        },
        inline: {
          default: 'none',
          hover: 'none',
          active: 'none',
          disabled: 'none',
        },
      },
    },
    text: {
      // Pattern: text.color.[variant].[subType].[state]
      // Example: text.color.primary.inline.hover
      color: {
        primary: {
          default: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          iconOnly: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          inline: {
            default: FOUNDATION_THEME.colors.primary[600],
            hover: FOUNDATION_THEME.colors.primary[600],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.primary[300],
          },
        },
        secondary: {
          default: {
            default: FOUNDATION_THEME.colors.gray[700],
            hover: FOUNDATION_THEME.colors.gray[600],
            active: FOUNDATION_THEME.colors.gray[600],
            disabled: FOUNDATION_THEME.colors.gray[300],
          },
          iconOnly: {
            default: FOUNDATION_THEME.colors.gray[600],
            hover: FOUNDATION_THEME.colors.gray[600],
            active: FOUNDATION_THEME.colors.gray[600],
            disabled: FOUNDATION_THEME.colors.gray[400],
          },
          inline: {
            default: FOUNDATION_THEME.colors.gray[600],
            hover: FOUNDATION_THEME.colors.gray[600],
            active: FOUNDATION_THEME.colors.gray[600],
            disabled: FOUNDATION_THEME.colors.gray[400],
          },
        },
        danger: {
          default: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          iconOnly: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          inline: {
            default: FOUNDATION_THEME.colors.red[600],
            hover: FOUNDATION_THEME.colors.red[600],
            active: FOUNDATION_THEME.colors.red[600],
            disabled: FOUNDATION_THEME.colors.red[400],
          },
        },
        success: {
          default: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          iconOnly: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          inline: {
            default: FOUNDATION_THEME.colors.green[600],
            hover: FOUNDATION_THEME.colors.green[600],
            active: FOUNDATION_THEME.colors.green[600],
            disabled: FOUNDATION_THEME.colors.green[400],
          },
        },
      },
      // Pattern: text.fontSize.[size] (size-dependent)
      fontSize: {
        sm: FOUNDATION_THEME.font.fontSize[14],
        md: FOUNDATION_THEME.font.fontSize[14],
        lg: FOUNDATION_THEME.font.fontSize[14],
      },
      // Pattern: text.fontWeight.[size] (size-dependent)
      fontWeight: {
        sm: FOUNDATION_THEME.font.weight[500],
        md: FOUNDATION_THEME.font.weight[500],
        lg: FOUNDATION_THEME.font.weight[500],
      },
      lineHeight: {
        sm: FOUNDATION_THEME.font.lineHeight[20],
        md: FOUNDATION_THEME.font.lineHeight[20],
        lg: FOUNDATION_THEME.font.lineHeight[20],
      },
    },
  },
}
