import {
  FOUNDATION_THEME,
  CardV2Orientation,
  CardV2Padding,
  CardV2Variant,
  type ResponsiveCardV2Tokens,
} from '@juspay/blend-design-system'

/**
 * `CARDV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/CardV2/cardV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.CARDV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
const lgTokens = {
  width: '100%',
  minWidth: '0',
  maxWidth: '100%',
  borderRadius: FOUNDATION_THEME.border.radius[12],
  border: {
    [CardV2Variant.OUTLINED]: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
    [CardV2Variant.ELEVATED]: `1px solid ${FOUNDATION_THEME.colors.gray[100]}`,
    [CardV2Variant.GHOST]: '1px solid transparent',
  },
  backgroundColor: {
    [CardV2Variant.OUTLINED]: FOUNDATION_THEME.colors.gray[0],
    [CardV2Variant.ELEVATED]: FOUNDATION_THEME.colors.gray[0],
    [CardV2Variant.GHOST]: 'transparent',
  },
  boxShadow: {
    [CardV2Variant.OUTLINED]: 'none',
    [CardV2Variant.ELEVATED]: FOUNDATION_THEME.shadows.sm,
    [CardV2Variant.GHOST]: 'none',
  },
  state: {
    hover: {
      border: `1px solid ${FOUNDATION_THEME.colors.gray[300]}`,
      boxShadow: FOUNDATION_THEME.shadows.sm,
    },
    selected: {
      border: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
      boxShadow: `0 0 0 3px ${FOUNDATION_THEME.colors.primary[50]}`,
    },
    focus: {
      outline: `2px solid ${FOUNDATION_THEME.colors.primary[500]}`,
      outlineOffset: FOUNDATION_THEME.unit[2],
    },
  },
  padding: {
    [CardV2Padding.NONE]: {
      x: '0',
      y: '0',
    },
    [CardV2Padding.COMPACT]: {
      x: FOUNDATION_THEME.unit[10],
      y: FOUNDATION_THEME.unit[10],
    },
    [CardV2Padding.COMFORTABLE]: {
      x: FOUNDATION_THEME.unit[12],
      y: FOUNDATION_THEME.unit[12],
    },
  },
  layout: {
    gap: FOUNDATION_THEME.unit[10],
    mediaGap: {
      [CardV2Orientation.VERTICAL]: FOUNDATION_THEME.unit[10],
      [CardV2Orientation.HORIZONTAL]: FOUNDATION_THEME.unit[12],
    },
  },
  media: {
    width: FOUNDATION_THEME.unit[64],
    height: FOUNDATION_THEME.unit[64],
    minHeight: '96px',
    borderRadius: FOUNDATION_THEME.border.radius[8],
    backgroundColor: FOUNDATION_THEME.colors.gray[50],
  },
  header: {
    gap: FOUNDATION_THEME.unit[6],
    eyebrow: {
      fontSize: FOUNDATION_THEME.font.fontSize[12],
      fontWeight: FOUNDATION_THEME.font.weight[600],
      lineHeight: FOUNDATION_THEME.font.lineHeight[18],
      color: FOUNDATION_THEME.colors.gray[500],
    },
    title: {
      fontSize: FOUNDATION_THEME.font.fontSize[16],
      fontWeight: FOUNDATION_THEME.font.weight[600],
      lineHeight: FOUNDATION_THEME.font.lineHeight[24],
      color: FOUNDATION_THEME.colors.gray[800],
    },
    subtitle: {
      fontSize: FOUNDATION_THEME.font.fontSize[14],
      fontWeight: FOUNDATION_THEME.font.weight[500],
      lineHeight: FOUNDATION_THEME.font.lineHeight[20],
      color: FOUNDATION_THEME.colors.gray[500],
    },
  },
  body: {
    gap: FOUNDATION_THEME.unit[10],
    description: {
      fontSize: FOUNDATION_THEME.font.fontSize[14],
      fontWeight: FOUNDATION_THEME.font.weight[400],
      lineHeight: FOUNDATION_THEME.font.lineHeight[20],
      color: FOUNDATION_THEME.colors.gray[600],
    },
  },
  footer: {
    gap: FOUNDATION_THEME.unit[8],
    paddingTop: FOUNDATION_THEME.unit[10],
    borderTop: `1px solid ${FOUNDATION_THEME.colors.gray[100]}`,
  },
  actions: {
    gap: FOUNDATION_THEME.unit[8],
  },
}

const smTokens = {
  ...lgTokens,
  borderRadius: FOUNDATION_THEME.border.radius[8],
  padding: {
    [CardV2Padding.NONE]: {
      x: '0',
      y: '0',
    },
    [CardV2Padding.COMPACT]: {
      x: FOUNDATION_THEME.unit[8],
      y: FOUNDATION_THEME.unit[8],
    },
    [CardV2Padding.COMFORTABLE]: {
      x: FOUNDATION_THEME.unit[10],
      y: FOUNDATION_THEME.unit[10],
    },
  },
  layout: {
    gap: FOUNDATION_THEME.unit[8],
    mediaGap: {
      [CardV2Orientation.VERTICAL]: FOUNDATION_THEME.unit[8],
      [CardV2Orientation.HORIZONTAL]: FOUNDATION_THEME.unit[10],
    },
  },
  media: {
    ...lgTokens.media,
    width: FOUNDATION_THEME.unit[56],
    height: FOUNDATION_THEME.unit[56],
    minHeight: '80px',
  },
  header: {
    ...lgTokens.header,
    gap: FOUNDATION_THEME.unit[4],
    title: {
      ...lgTokens.header.title,
      fontSize: FOUNDATION_THEME.font.fontSize[14],
      lineHeight: FOUNDATION_THEME.font.lineHeight[20],
    },
    subtitle: {
      ...lgTokens.header.subtitle,
      fontSize: FOUNDATION_THEME.font.fontSize[12],
      lineHeight: FOUNDATION_THEME.font.lineHeight[18],
    },
  },
  body: {
    ...lgTokens.body,
    gap: FOUNDATION_THEME.unit[8],
    description: {
      ...lgTokens.body.description,
      fontSize: FOUNDATION_THEME.font.fontSize[12],
      lineHeight: FOUNDATION_THEME.font.lineHeight[18],
    },
  },
  footer: {
    ...lgTokens.footer,
    gap: FOUNDATION_THEME.unit[6],
    paddingTop: FOUNDATION_THEME.unit[8],
  },
  actions: {
    gap: FOUNDATION_THEME.unit[6],
  },
}

export const CARDV2_TOKENS: ResponsiveCardV2Tokens = {
  sm: smTokens,
  lg: lgTokens,
}
