import { FOUNDATION_THEME, type ResponsiveCheckboxV2Tokens } from '@juspay/blend-design-system'

/**
 * `CHECKBOXV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/SelectorV2/CheckboxV2/checkboxV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.CHECKBOXV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const CHECKBOXV2_TOKENS: ResponsiveCheckboxV2Tokens = {
  sm: {
    gap: FOUNDATION_THEME.unit[8],
    checkbox: {
      width: {
        sm: FOUNDATION_THEME.unit[16],
        md: FOUNDATION_THEME.unit[20],
        lg: FOUNDATION_THEME.unit[24],
      },
      height: {
        sm: FOUNDATION_THEME.unit[16],
        md: FOUNDATION_THEME.unit[20],
        lg: FOUNDATION_THEME.unit[24],
      },
      opacity: FOUNDATION_THEME.opacity[70],
      backgroundColor: {
        unchecked: {
          default: FOUNDATION_THEME.colors.gray[0],
          hover: FOUNDATION_THEME.colors.gray[150],
          disabled: FOUNDATION_THEME.colors.gray[100],
          error: FOUNDATION_THEME.colors.gray[0],
        },
        checked: {
          default: FOUNDATION_THEME.colors.primary[600],
          hover: FOUNDATION_THEME.colors.primary[600],
          disabled: FOUNDATION_THEME.colors.primary[200],
          error: FOUNDATION_THEME.colors.primary[500],
        },
        indeterminate: {
          default: FOUNDATION_THEME.colors.primary[500],
          hover: FOUNDATION_THEME.colors.primary[600],
          disabled: FOUNDATION_THEME.colors.primary[200],
          error: FOUNDATION_THEME.colors.primary[500],
        },
      },

      borderRadius: {
        sm: FOUNDATION_THEME.border.radius[4],
        md: FOUNDATION_THEME.border.radius[4],
        lg: FOUNDATION_THEME.border.radius[4],
      },
      border: {
        unchecked: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[300]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[400]}`,
          disabled: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          error: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        },
        checked: {
          default: 'transparent',
          hover: 'transparent',
          disabled: 'transparent',
          error: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        },
        indeterminate: {
          default: 'transparent',
          hover: 'transparent',
          disabled: 'transparent',
          error: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        },
      },

      outline: `1px solid ${FOUNDATION_THEME.colors.primary[200]}`,
      outlineOffset: FOUNDATION_THEME.unit[2],
      boxShadow: `0 0 0 2px ${FOUNDATION_THEME.colors.primary[100]}`,

      icon: {
        color: {
          checked: {
            default: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          indeterminate: {
            default: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
        },
        width: {
          sm: FOUNDATION_THEME.unit[12],
          md: FOUNDATION_THEME.unit[14],
          lg: FOUNDATION_THEME.unit[16],
        },
        height: {
          sm: FOUNDATION_THEME.unit[12],
          md: FOUNDATION_THEME.unit[14],
          lg: FOUNDATION_THEME.unit[16],
        },
        strokeWidth: {
          sm: 2.5,
          md: 2.5,
          lg: 2.5,
        },
      },
    },

    content: {
      gap: FOUNDATION_THEME.unit[0],
      label: {
        gap: FOUNDATION_THEME.unit[0],
        color: {
          default: FOUNDATION_THEME.colors.gray[700],
          hover: FOUNDATION_THEME.colors.gray[700],
          disabled: FOUNDATION_THEME.colors.gray[300],
          error: FOUNDATION_THEME.colors.red[600],
          focus: FOUNDATION_THEME.colors.gray[700],
        },

        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[12],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[16],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[14],
          md: FOUNDATION_THEME.font.lineHeight[16],
          lg: FOUNDATION_THEME.font.lineHeight[16],
        },
        slot: {
          maxHeight: {
            sm: FOUNDATION_THEME.unit[12],
            md: FOUNDATION_THEME.unit[14],
            lg: FOUNDATION_THEME.unit[16],
          },
        },
      },
      subLabel: {
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[200],
          error: FOUNDATION_THEME.colors.red[500],
          hover: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[700],
        },

        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[12],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[16],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[400],
          md: FOUNDATION_THEME.font.weight[400],
          lg: FOUNDATION_THEME.font.weight[400],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[12],
          md: FOUNDATION_THEME.font.lineHeight[16],
          lg: FOUNDATION_THEME.font.lineHeight[16],
        },
      },
      required: {
        color: FOUNDATION_THEME.colors.red[600],
      },
    },
  },
  lg: {
    gap: FOUNDATION_THEME.unit[8],
    checkbox: {
      height: {
        sm: FOUNDATION_THEME.unit[14],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[24],
      },
      width: {
        sm: FOUNDATION_THEME.unit[14],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[24],
      },
      opacity: FOUNDATION_THEME.opacity[70],
      backgroundColor: {
        unchecked: {
          default: FOUNDATION_THEME.colors.gray[0],
          hover: FOUNDATION_THEME.colors.gray[150],
          disabled: FOUNDATION_THEME.colors.gray[100],
          error: FOUNDATION_THEME.colors.gray[0],
        },
        checked: {
          default: FOUNDATION_THEME.colors.primary[600],
          hover: FOUNDATION_THEME.colors.primary[600],
          disabled: FOUNDATION_THEME.colors.primary[200],
          error: FOUNDATION_THEME.colors.primary[500],
        },
        indeterminate: {
          default: FOUNDATION_THEME.colors.primary[500],
          hover: FOUNDATION_THEME.colors.primary[600],
          disabled: FOUNDATION_THEME.colors.primary[200],
          error: FOUNDATION_THEME.colors.primary[500],
        },
      },
      borderRadius: {
        sm: FOUNDATION_THEME.border.radius[4],
        md: FOUNDATION_THEME.border.radius[4],
        lg: FOUNDATION_THEME.border.radius[4],
      },
      border: {
        unchecked: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[300]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[400]}`,
          disabled: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          error: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        },
        checked: {
          default: 'transparent',
          hover: 'transparent',
          disabled: 'transparent',
          error: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        },
        indeterminate: {
          default: 'transparent',
          hover: 'transparent',
          disabled: 'transparent',
          error: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        },
      },
      outline: `1px solid ${FOUNDATION_THEME.colors.primary[200]}`,
      outlineOffset: FOUNDATION_THEME.unit[2],
      boxShadow: `0 0 0 2px ${FOUNDATION_THEME.colors.primary[100]}`,
      icon: {
        color: {
          checked: {
            default: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
          indeterminate: {
            default: FOUNDATION_THEME.colors.gray[0],
            disabled: FOUNDATION_THEME.colors.gray[0],
          },
        },

        width: {
          sm: FOUNDATION_THEME.unit[10],
          md: FOUNDATION_THEME.unit[12],
          lg: FOUNDATION_THEME.unit[16],
        },
        height: {
          sm: FOUNDATION_THEME.unit[10],
          md: FOUNDATION_THEME.unit[12],
          lg: FOUNDATION_THEME.unit[16],
        },
        strokeWidth: {
          sm: 2.5,
          md: 2.5,
          lg: 2.5,
        },
      },
    },
    content: {
      gap: FOUNDATION_THEME.unit[6],
      label: {
        gap: FOUNDATION_THEME.unit[6],
        color: {
          default: FOUNDATION_THEME.colors.gray[700],
          hover: FOUNDATION_THEME.colors.gray[800],
          disabled: FOUNDATION_THEME.colors.gray[300],
          error: FOUNDATION_THEME.colors.red[600],
          focus: FOUNDATION_THEME.colors.gray[700],
        },

        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[12],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[16],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[12],
          md: FOUNDATION_THEME.font.lineHeight[16],
          lg: FOUNDATION_THEME.font.lineHeight[16],
        },
        slot: {
          maxHeight: {
            sm: FOUNDATION_THEME.unit[12],
            md: FOUNDATION_THEME.unit[14],
            lg: FOUNDATION_THEME.unit[16],
          },
        },
      },
      subLabel: {
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[500],
          disabled: FOUNDATION_THEME.colors.gray[200],
          error: FOUNDATION_THEME.colors.red[500],
          focus: FOUNDATION_THEME.colors.gray[700],
        },

        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[12],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[16],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[400],
          md: FOUNDATION_THEME.font.weight[400],
          lg: FOUNDATION_THEME.font.weight[400],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[12],
          md: FOUNDATION_THEME.font.lineHeight[16],
          lg: FOUNDATION_THEME.font.lineHeight[16],
        },
      },
      required: {
        color: FOUNDATION_THEME.colors.red[600],
      },
    },
  },
}
