import { FOUNDATION_THEME, type DrawerTokensType } from '@juspay/blend-design-system'

/**
 * `DRAWER` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/Drawer/drawer.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.DRAWER ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const DRAWER_TOKENS: Record<'sm' | 'lg', DrawerTokensType> = {
  sm: {
    // Base properties (shared)
    borderRadius: {
      topLeft: FOUNDATION_THEME.border.radius[16],
      topRight: FOUNDATION_THEME.border.radius[16],
      bottomLeft: FOUNDATION_THEME.border.radius[16],
      bottomRight: FOUNDATION_THEME.border.radius[16],
    },
    // border: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,

    overlay: {
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    offset: {
      top: '74px',
      bottom: FOUNDATION_THEME.unit[16],
      left: FOUNDATION_THEME.unit[16],
      right: FOUNDATION_THEME.unit[16],
    },
    content: {
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
      padding: {
        x: FOUNDATION_THEME.unit[16],
        y: FOUNDATION_THEME.unit[16],
      },
      handle: {
        backgroundColor: FOUNDATION_THEME.colors.gray[300],
        borderRadius: FOUNDATION_THEME.border.radius.full,
        width: FOUNDATION_THEME.unit[48],
        height: FOUNDATION_THEME.unit[6],
      },
    },
  },
  lg: {
    // Base properties (shared)
    borderRadius: {
      topLeft: FOUNDATION_THEME.border.radius[16],
      topRight: FOUNDATION_THEME.border.radius[16],
      bottomLeft: FOUNDATION_THEME.border.radius[16],
      bottomRight: FOUNDATION_THEME.border.radius[16],
    },
    // border: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,

    overlay: {
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    offset: {
      top: '74px',
      bottom: FOUNDATION_THEME.unit[16],
      left: FOUNDATION_THEME.unit[16],
      right: FOUNDATION_THEME.unit[16],
    },
    content: {
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
      padding: {
        x: FOUNDATION_THEME.unit[20],
        y: FOUNDATION_THEME.unit[20],
      },
      handle: {
        backgroundColor: FOUNDATION_THEME.colors.gray[300],
        borderRadius: FOUNDATION_THEME.border.radius.full,
        width: FOUNDATION_THEME.unit[48],
        height: FOUNDATION_THEME.unit[6],
      },
    },
  },
}
