import {
  FOUNDATION_THEME,
  MenuV2ItemActionType,
  MenuV2ItemVariant,
  type ResponsiveMenuV2TokensType,
} from '@juspay/blend-design-system'

/**
 * `MENU_V2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/MenuV2/menuV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.MENU_V2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const MENU_V2_TOKENS: ResponsiveMenuV2TokensType = {
  sm: {
    backgroundColor: FOUNDATION_THEME.colors.gray[0],
    border: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
    borderRadius: FOUNDATION_THEME.unit[8],
    boxShadow: FOUNDATION_THEME.shadows.sm,
    zIndex: FOUNDATION_THEME.zIndex[101],

    minWidth: 200,
    maxWidth: 280,

    // Half of Blend's 6: MenuV2Content.tsx applies paddingTop twice, once on the
    // popover (:220) and again on the list inside it (:320), so the first item sat 12px
    // under the border against 6px of bottom padding. 3 + 3 lands it at 6 all round.
    paddingTop: FOUNDATION_THEME.unit[3],
    paddingRight: FOUNDATION_THEME.unit[6],
    paddingBottom: FOUNDATION_THEME.unit[6],
    paddingLeft: FOUNDATION_THEME.unit[6],

    searchIcon: {
      width: FOUNDATION_THEME.unit[16],
    },

    group: {
      label: {
        fontSize: FOUNDATION_THEME.font.size.body.sm.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[400],
        lineHeight: FOUNDATION_THEME.font.lineHeight[14],
        color: FOUNDATION_THEME.colors.gray[400],

        paddingTop: FOUNDATION_THEME.unit[6],
        paddingRight: FOUNDATION_THEME.unit[8],
        paddingBottom: FOUNDATION_THEME.unit[6],
        paddingLeft: FOUNDATION_THEME.unit[8],

        marginTop: FOUNDATION_THEME.unit[0],
        marginRight: FOUNDATION_THEME.unit[6],
        marginBottom: FOUNDATION_THEME.unit[0],
        marginLeft: FOUNDATION_THEME.unit[6],
      },

      item: {
        paddingTop: FOUNDATION_THEME.unit[8],
        paddingRight: FOUNDATION_THEME.unit[8],
        paddingBottom: FOUNDATION_THEME.unit[8],
        paddingLeft: FOUNDATION_THEME.unit[8],

        marginTop: FOUNDATION_THEME.unit[0],
        marginRight: FOUNDATION_THEME.unit[4],
        marginBottom: FOUNDATION_THEME.unit[0],
        marginLeft: FOUNDATION_THEME.unit[4],

        borderRadius: FOUNDATION_THEME.unit[4],
        gap: FOUNDATION_THEME.unit[4],

        backgroundColor: {
          [MenuV2ItemVariant.DEFAULT]: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[50],
            active: FOUNDATION_THEME.colors.gray[50],
            focus: FOUNDATION_THEME.colors.gray[50],
            focusVisible: FOUNDATION_THEME.colors.gray[50],
            disabled: FOUNDATION_THEME.colors.gray[0],
            selected: FOUNDATION_THEME.colors.gray[0],
          },
          [MenuV2ItemVariant.ACTION]: {
            [MenuV2ItemActionType.PRIMARY]: {
              default: FOUNDATION_THEME.colors.primary[50],
              hover: FOUNDATION_THEME.colors.primary[100],
              active: FOUNDATION_THEME.colors.primary[50],
              focus: FOUNDATION_THEME.colors.primary[100],
              focusVisible: FOUNDATION_THEME.colors.primary[100],
              disabled: FOUNDATION_THEME.colors.gray[0],
              selected: FOUNDATION_THEME.colors.primary[50],
            },
            [MenuV2ItemActionType.DANGER]: {
              default: FOUNDATION_THEME.colors.red[50],
              hover: FOUNDATION_THEME.colors.red[100],
              active: FOUNDATION_THEME.colors.red[100],
              focus: FOUNDATION_THEME.colors.red[100],
              focusVisible: FOUNDATION_THEME.colors.red[100],
              disabled: FOUNDATION_THEME.colors.gray[0],
              selected: FOUNDATION_THEME.colors.red[50],
            },
          },
        },

        text: {
          fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[500],
          lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          color: {
            [MenuV2ItemVariant.DEFAULT]: {
              default: FOUNDATION_THEME.colors.gray[600],
              hover: FOUNDATION_THEME.colors.gray[600],
              active: FOUNDATION_THEME.colors.gray[600],
              focus: FOUNDATION_THEME.colors.gray[600],
              focusVisible: FOUNDATION_THEME.colors.gray[600],
              disabled: FOUNDATION_THEME.colors.gray[400],
              selected: FOUNDATION_THEME.colors.gray[600],
            },
            [MenuV2ItemVariant.ACTION]: {
              [MenuV2ItemActionType.PRIMARY]: {
                default: FOUNDATION_THEME.colors.primary[600],
                hover: FOUNDATION_THEME.colors.primary[600],
                active: FOUNDATION_THEME.colors.primary[600],
                focus: FOUNDATION_THEME.colors.primary[600],
                focusVisible: FOUNDATION_THEME.colors.primary[600],
                disabled: FOUNDATION_THEME.colors.gray[400],
                selected: FOUNDATION_THEME.colors.primary[600],
              },
              [MenuV2ItemActionType.DANGER]: {
                default: FOUNDATION_THEME.colors.red[600],
                hover: FOUNDATION_THEME.colors.red[600],
                active: FOUNDATION_THEME.colors.red[600],
                focus: FOUNDATION_THEME.colors.red[600],
                focusVisible: FOUNDATION_THEME.colors.red[600],
                disabled: FOUNDATION_THEME.colors.red[400],
                selected: FOUNDATION_THEME.colors.red[600],
              },
            },
          },

          subText: {
            fontSize: FOUNDATION_THEME.font.size.body.sm.fontSize,
            fontWeight: FOUNDATION_THEME.font.weight[400],
            lineHeight: FOUNDATION_THEME.font.lineHeight[14],
            color: {
              [MenuV2ItemVariant.DEFAULT]: {
                default: FOUNDATION_THEME.colors.gray[400],
                hover: FOUNDATION_THEME.colors.gray[400],
                active: FOUNDATION_THEME.colors.gray[400],
                focus: FOUNDATION_THEME.colors.gray[400],
                focusVisible: FOUNDATION_THEME.colors.gray[400],
                disabled: FOUNDATION_THEME.colors.gray[400],
                selected: FOUNDATION_THEME.colors.gray[400],
              },
              [MenuV2ItemVariant.ACTION]: {
                [MenuV2ItemActionType.PRIMARY]: {
                  default: FOUNDATION_THEME.colors.primary[400],
                  hover: FOUNDATION_THEME.colors.primary[400],
                  active: FOUNDATION_THEME.colors.primary[400],
                  focus: FOUNDATION_THEME.colors.primary[400],
                  focusVisible: FOUNDATION_THEME.colors.primary[400],
                  disabled: FOUNDATION_THEME.colors.gray[400],
                  selected: FOUNDATION_THEME.colors.primary[400],
                },
                [MenuV2ItemActionType.DANGER]: {
                  default: FOUNDATION_THEME.colors.red[400],
                  hover: FOUNDATION_THEME.colors.red[400],
                  active: FOUNDATION_THEME.colors.red[400],
                  focus: FOUNDATION_THEME.colors.red[400],
                  focusVisible: FOUNDATION_THEME.colors.red[400],
                  disabled: FOUNDATION_THEME.colors.red[400],
                  selected: FOUNDATION_THEME.colors.red[400],
                },
              },
            },
          },

          leftSlot: {
            maxWidth: FOUNDATION_THEME.unit[16],
            maxHeight: FOUNDATION_THEME.unit[16],
          },

          rightChevron: {
            color: FOUNDATION_THEME.colors.gray[500],
            width: FOUNDATION_THEME.unit[16],
          },
        },
      },
    },

    separator: {
      color: FOUNDATION_THEME.colors.gray[200],
      height: FOUNDATION_THEME.unit[1],
      marginTop: FOUNDATION_THEME.unit[6],
      marginRight: FOUNDATION_THEME.unit[0],
      marginBottom: FOUNDATION_THEME.unit[6],
      marginLeft: FOUNDATION_THEME.unit[0],
    },
  },
  lg: {
    backgroundColor: FOUNDATION_THEME.colors.gray[0],
    border: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
    borderRadius: FOUNDATION_THEME.unit[8],
    boxShadow: FOUNDATION_THEME.shadows.sm,
    zIndex: FOUNDATION_THEME.zIndex[101],

    minWidth: 200,
    maxWidth: 280,

    // Half of Blend's 6: MenuV2Content.tsx applies paddingTop twice, once on the
    // popover (:220) and again on the list inside it (:320), so the first item sat 12px
    // under the border against 6px of bottom padding. 3 + 3 lands it at 6 all round.
    paddingTop: FOUNDATION_THEME.unit[3],
    paddingRight: FOUNDATION_THEME.unit[6],
    paddingBottom: FOUNDATION_THEME.unit[6],
    paddingLeft: FOUNDATION_THEME.unit[6],

    searchIcon: {
      width: FOUNDATION_THEME.unit[16],
    },

    group: {
      label: {
        fontSize: FOUNDATION_THEME.font.size.body.sm.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[400],
        lineHeight: FOUNDATION_THEME.font.lineHeight[14],
        color: FOUNDATION_THEME.colors.gray[400],

        paddingTop: FOUNDATION_THEME.unit[6],
        paddingRight: FOUNDATION_THEME.unit[8],
        paddingBottom: FOUNDATION_THEME.unit[6],
        paddingLeft: FOUNDATION_THEME.unit[8],

        marginTop: FOUNDATION_THEME.unit[0],
        marginRight: FOUNDATION_THEME.unit[6],
        marginBottom: FOUNDATION_THEME.unit[0],
        marginLeft: FOUNDATION_THEME.unit[6],
      },

      item: {
        paddingTop: FOUNDATION_THEME.unit[8],
        paddingRight: FOUNDATION_THEME.unit[8],
        paddingBottom: FOUNDATION_THEME.unit[8],
        paddingLeft: FOUNDATION_THEME.unit[8],

        marginTop: FOUNDATION_THEME.unit[0],
        marginRight: FOUNDATION_THEME.unit[4],
        marginBottom: FOUNDATION_THEME.unit[0],
        marginLeft: FOUNDATION_THEME.unit[4],

        borderRadius: FOUNDATION_THEME.unit[4],
        gap: FOUNDATION_THEME.unit[4],

        backgroundColor: {
          [MenuV2ItemVariant.DEFAULT]: {
            default: FOUNDATION_THEME.colors.gray[0],
            hover: FOUNDATION_THEME.colors.gray[50],
            active: FOUNDATION_THEME.colors.gray[50],
            focus: FOUNDATION_THEME.colors.gray[50],
            focusVisible: FOUNDATION_THEME.colors.gray[50],
            disabled: FOUNDATION_THEME.colors.gray[0],
            selected: FOUNDATION_THEME.colors.gray[0],
          },
          [MenuV2ItemVariant.ACTION]: {
            [MenuV2ItemActionType.PRIMARY]: {
              default: FOUNDATION_THEME.colors.primary[50],
              hover: FOUNDATION_THEME.colors.primary[100],
              active: FOUNDATION_THEME.colors.primary[50],
              focus: FOUNDATION_THEME.colors.primary[100],
              focusVisible: FOUNDATION_THEME.colors.primary[100],
              disabled: FOUNDATION_THEME.colors.gray[0],
              selected: FOUNDATION_THEME.colors.primary[50],
            },
            [MenuV2ItemActionType.DANGER]: {
              default: FOUNDATION_THEME.colors.red[50],
              hover: FOUNDATION_THEME.colors.red[100],
              active: FOUNDATION_THEME.colors.red[100],
              focus: FOUNDATION_THEME.colors.red[100],
              focusVisible: FOUNDATION_THEME.colors.red[100],
              disabled: FOUNDATION_THEME.colors.gray[0],
              selected: FOUNDATION_THEME.colors.red[50],
            },
          },
        },

        text: {
          fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[500],
          lineHeight: FOUNDATION_THEME.font.lineHeight[16],
          color: {
            [MenuV2ItemVariant.DEFAULT]: {
              default: FOUNDATION_THEME.colors.gray[600],
              hover: FOUNDATION_THEME.colors.gray[600],
              active: FOUNDATION_THEME.colors.gray[600],
              focus: FOUNDATION_THEME.colors.gray[600],
              focusVisible: FOUNDATION_THEME.colors.gray[600],
              disabled: FOUNDATION_THEME.colors.gray[400],
              selected: FOUNDATION_THEME.colors.gray[600],
            },
            [MenuV2ItemVariant.ACTION]: {
              [MenuV2ItemActionType.PRIMARY]: {
                default: FOUNDATION_THEME.colors.primary[600],
                hover: FOUNDATION_THEME.colors.primary[600],
                active: FOUNDATION_THEME.colors.primary[600],
                focus: FOUNDATION_THEME.colors.primary[600],
                focusVisible: FOUNDATION_THEME.colors.primary[600],
                disabled: FOUNDATION_THEME.colors.gray[400],
                selected: FOUNDATION_THEME.colors.primary[600],
              },
              [MenuV2ItemActionType.DANGER]: {
                default: FOUNDATION_THEME.colors.red[600],
                hover: FOUNDATION_THEME.colors.red[600],
                active: FOUNDATION_THEME.colors.red[600],
                focus: FOUNDATION_THEME.colors.red[600],
                focusVisible: FOUNDATION_THEME.colors.red[600],
                disabled: FOUNDATION_THEME.colors.red[400],
                selected: FOUNDATION_THEME.colors.red[600],
              },
            },
          },

          subText: {
            fontSize: FOUNDATION_THEME.font.size.body.sm.fontSize,
            fontWeight: FOUNDATION_THEME.font.weight[400],
            lineHeight: FOUNDATION_THEME.font.lineHeight[14],
            color: {
              [MenuV2ItemVariant.DEFAULT]: {
                default: FOUNDATION_THEME.colors.gray[400],
                hover: FOUNDATION_THEME.colors.gray[400],
                active: FOUNDATION_THEME.colors.gray[400],
                focus: FOUNDATION_THEME.colors.gray[400],
                focusVisible: FOUNDATION_THEME.colors.gray[400],
                disabled: FOUNDATION_THEME.colors.gray[400],
                selected: FOUNDATION_THEME.colors.gray[400],
              },
              [MenuV2ItemVariant.ACTION]: {
                [MenuV2ItemActionType.PRIMARY]: {
                  default: FOUNDATION_THEME.colors.primary[400],
                  hover: FOUNDATION_THEME.colors.primary[400],
                  active: FOUNDATION_THEME.colors.primary[400],
                  focus: FOUNDATION_THEME.colors.primary[400],
                  focusVisible: FOUNDATION_THEME.colors.primary[400],
                  disabled: FOUNDATION_THEME.colors.gray[400],
                  selected: FOUNDATION_THEME.colors.primary[400],
                },
                [MenuV2ItemActionType.DANGER]: {
                  default: FOUNDATION_THEME.colors.red[400],
                  hover: FOUNDATION_THEME.colors.red[400],
                  active: FOUNDATION_THEME.colors.red[400],
                  focus: FOUNDATION_THEME.colors.red[400],
                  focusVisible: FOUNDATION_THEME.colors.red[400],
                  disabled: FOUNDATION_THEME.colors.red[400],
                  selected: FOUNDATION_THEME.colors.red[400],
                },
              },
            },
          },

          leftSlot: {
            maxWidth: FOUNDATION_THEME.unit[16],
            maxHeight: FOUNDATION_THEME.unit[16],
          },

          rightChevron: {
            color: FOUNDATION_THEME.colors.gray[500],
            width: FOUNDATION_THEME.unit[16],
          },
        },
      },
    },
    separator: {
      color: FOUNDATION_THEME.colors.gray[200],
      height: FOUNDATION_THEME.unit[1],
      marginTop: FOUNDATION_THEME.unit[6],
      marginRight: FOUNDATION_THEME.unit[0],
      marginBottom: FOUNDATION_THEME.unit[6],
      marginLeft: FOUNDATION_THEME.unit[0],
    },
  },
}
