import { FOUNDATION_THEME, type ResponsiveModalV2Tokens } from '@juspay/blend-design-system'

/**
 * `MODALV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/ModalV2/modalV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.MODALV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const MODALV2_TOKENS: ResponsiveModalV2Tokens = {
  sm: {
    paddingTop: FOUNDATION_THEME.unit[16],
    paddingRight: FOUNDATION_THEME.unit[16],
    paddingBottom: FOUNDATION_THEME.unit[16],
    paddingLeft: FOUNDATION_THEME.unit[16],
    boxShadow: FOUNDATION_THEME.shadows.xs,
    borderRadius: FOUNDATION_THEME.border.radius[16],
    backgroundColor: FOUNDATION_THEME.colors.gray[0],
    overlay: {
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      offset: FOUNDATION_THEME.unit[16],
    },
    skeleton: {
      header: {
        gap: FOUNDATION_THEME.unit[16],
        paddingTop: FOUNDATION_THEME.unit[20],
        paddingRight: FOUNDATION_THEME.unit[20],
        paddingBottom: FOUNDATION_THEME.unit[20],
        paddingLeft: FOUNDATION_THEME.unit[20],
        borderBottom: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        width: '60%',
        height: 24,
        borderRadius: FOUNDATION_THEME.border.radius[4],
      },
      body: {
        gap: FOUNDATION_THEME.unit[12],
        width: '100%',
        height: 300,
        borderRadius: FOUNDATION_THEME.border.radius[4],
      },
    },
    divider: {
      borderColor: FOUNDATION_THEME.colors.gray[200],
    },
    header: {
      gap: FOUNDATION_THEME.unit[16],
      paddingTop: FOUNDATION_THEME.unit[16],
      paddingRight: FOUNDATION_THEME.unit[16],
      paddingBottom: FOUNDATION_THEME.unit[16],
      paddingLeft: FOUNDATION_THEME.unit[16],
      maxHeight: '20vh',
      borderBottom: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
      borderTopLeftRadius: FOUNDATION_THEME.border.radius[16],
      borderTopRightRadius: FOUNDATION_THEME.border.radius[16],
      slot: {
        gap: FOUNDATION_THEME.unit[8],
      },
      text: {
        title: {
          color: FOUNDATION_THEME.colors.gray[700],
          fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[600],
          lineHeight: FOUNDATION_THEME.font.lineHeight[20],
        },
        subtitle: {
          color: FOUNDATION_THEME.colors.gray[600],
          fontSize: FOUNDATION_THEME.font.size.body.sm.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[400],
          lineHeight: FOUNDATION_THEME.font.lineHeight[20],
        },
      },
    },

    body: {
      paddingTop: FOUNDATION_THEME.unit[16],
      paddingRight: FOUNDATION_THEME.unit[16],
      paddingBottom: FOUNDATION_THEME.unit[16],
      paddingLeft: FOUNDATION_THEME.unit[16],
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
    },

    footer: {
      paddingTop: FOUNDATION_THEME.unit[16],
      paddingRight: FOUNDATION_THEME.unit[16],
      paddingBottom: FOUNDATION_THEME.unit[16],
      paddingLeft: FOUNDATION_THEME.unit[16],
      borderTop: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
      gap: FOUNDATION_THEME.unit[12],
    },
    closeButton: {
      color: FOUNDATION_THEME.colors.gray[500],
      width: FOUNDATION_THEME.unit[16],
      height: FOUNDATION_THEME.unit[16],
    },
  },
  lg: {
    backgroundColor: FOUNDATION_THEME.colors.gray[0],
    paddingTop: FOUNDATION_THEME.unit[16],
    paddingRight: FOUNDATION_THEME.unit[16],
    paddingBottom: FOUNDATION_THEME.unit[16],
    paddingLeft: FOUNDATION_THEME.unit[16],
    boxShadow: FOUNDATION_THEME.shadows.lg,
    borderRadius: FOUNDATION_THEME.border.radius[16],
    overlay: {
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      offset: FOUNDATION_THEME.unit[16],
    },
    divider: {
      borderColor: FOUNDATION_THEME.colors.gray[200],
    },
    header: {
      gap: FOUNDATION_THEME.unit[16],
      paddingTop: FOUNDATION_THEME.unit[20],
      paddingRight: FOUNDATION_THEME.unit[20],
      paddingBottom: FOUNDATION_THEME.unit[20],
      paddingLeft: FOUNDATION_THEME.unit[20],
      maxHeight: '20vh',
      borderBottom: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
      borderTopLeftRadius: FOUNDATION_THEME.border.radius[16],
      borderTopRightRadius: FOUNDATION_THEME.border.radius[16],
      slot: {
        gap: FOUNDATION_THEME.unit[8],
      },
      text: {
        title: {
          color: FOUNDATION_THEME.colors.gray[700],
          fontSize: FOUNDATION_THEME.font.size.body.lg.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[600],
          lineHeight: FOUNDATION_THEME.font.lineHeight[20],
        },
        subtitle: {
          color: FOUNDATION_THEME.colors.gray[600],
          fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
          fontWeight: FOUNDATION_THEME.font.weight[400],
          lineHeight: FOUNDATION_THEME.font.lineHeight[20],
        },
      },
    },
    skeleton: {
      header: {
        gap: FOUNDATION_THEME.unit[16],
        paddingTop: FOUNDATION_THEME.unit[20],
        paddingRight: FOUNDATION_THEME.unit[20],
        paddingBottom: FOUNDATION_THEME.unit[20],
        paddingLeft: FOUNDATION_THEME.unit[20],
        borderBottom: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        width: '60%',
        height: 24,
        borderRadius: FOUNDATION_THEME.border.radius[4],
      },
      body: {
        gap: FOUNDATION_THEME.unit[12],
        width: '100%',
        height: 300,
        borderRadius: FOUNDATION_THEME.border.radius[4],
      },
    },

    body: {
      paddingTop: FOUNDATION_THEME.unit[20],
      paddingRight: FOUNDATION_THEME.unit[20],
      paddingBottom: FOUNDATION_THEME.unit[20],
      paddingLeft: FOUNDATION_THEME.unit[20],
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
    },

    footer: {
      paddingTop: FOUNDATION_THEME.unit[20],
      paddingRight: FOUNDATION_THEME.unit[20],
      paddingBottom: FOUNDATION_THEME.unit[20],
      paddingLeft: FOUNDATION_THEME.unit[20],
      borderTop: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
      gap: FOUNDATION_THEME.unit[16],
    },
    closeButton: {
      color: FOUNDATION_THEME.colors.gray[500],
      width: FOUNDATION_THEME.unit[16],
      height: FOUNDATION_THEME.unit[16],
    },
  },
}
