import { FOUNDATION_THEME, type ResponsivePopoverV2Tokens } from '@juspay/blend-design-system'

/**
 * `POPOVERV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/PopoverV2/popoverV2.light.tokens.tsx. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.POPOVERV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const POPOVERV2_TOKENS: ResponsivePopoverV2Tokens = {
  sm: {
    // background (size-independent)
    background: FOUNDATION_THEME.colors.gray[0],
    // border (size-independent)
    border: FOUNDATION_THEME.border.radius[8],
    // shadow (size-independent)
    shadow: FOUNDATION_THEME.shadows,
    // gap.[size]
    gap: {
      sm: FOUNDATION_THEME.unit[12],
      md: FOUNDATION_THEME.unit[12],
      lg: FOUNDATION_THEME.unit[12],
    },
    // zIndex (size-independent)
    zIndex: 101,
    // borderRadius.[size]
    borderRadius: {
      sm: FOUNDATION_THEME.border.radius[8],
      md: FOUNDATION_THEME.border.radius[8],
      lg: FOUNDATION_THEME.border.radius[8],
    },
    // padding.[side].[size]
    padding: {
      left: {
        sm: FOUNDATION_THEME.unit[16],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[16],
      },
      right: {
        sm: FOUNDATION_THEME.unit[16],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[16],
      },
      top: {
        sm: FOUNDATION_THEME.unit[12],
        md: FOUNDATION_THEME.unit[12],
        lg: FOUNDATION_THEME.unit[12],
      },
      bottom: {
        sm: FOUNDATION_THEME.unit[16],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[16],
      },
    },
    TopContainer: {
      gap: {
        sm: FOUNDATION_THEME.unit[8],
        md: FOUNDATION_THEME.unit[8],
        lg: FOUNDATION_THEME.unit[8],
      },
      heading: {
        // heading.fontSize.[size]
        fontSize: {
          sm: FOUNDATION_THEME.font.size.body.md.fontSize,
          md: FOUNDATION_THEME.font.size.body.lg.fontSize,
          lg: FOUNDATION_THEME.font.size.body.lg.fontSize,
        },
        // heading.fontWeight.[size]
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[600],
          md: FOUNDATION_THEME.font.weight[600],
          lg: FOUNDATION_THEME.font.weight[600],
        },
        // heading.color (size-independent)
        color: FOUNDATION_THEME.colors.gray[900],
        // heading.lineHeight.[size]
        lineHeight: {
          sm: FOUNDATION_THEME.unit[24],
          md: FOUNDATION_THEME.unit[24],
          lg: FOUNDATION_THEME.unit[24],
        },

        IconSize: {
          sm: FOUNDATION_THEME.font.fontSize[18],
          md: FOUNDATION_THEME.font.fontSize[18],
          lg: FOUNDATION_THEME.font.fontSize[18],
        },
      },
      description: {
        // description.fontSize.[size]
        fontSize: {
          sm: FOUNDATION_THEME.font.size.body.sm.fontSize,
          md: FOUNDATION_THEME.font.size.body.md.fontSize,
          lg: FOUNDATION_THEME.font.size.body.lg.fontSize,
        },
        // description.fontWeight.[size]
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        // description.color (size-independent)
        color: FOUNDATION_THEME.colors.gray[500],
        // description.lineHeight.[size]
        lineHeight: {
          sm: FOUNDATION_THEME.unit[16],
          md: FOUNDATION_THEME.unit[16],
          lg: FOUNDATION_THEME.unit[16],
        },
      },
    },
    bottomContainer: {
      // footer.gap.[size]
      gap: {
        sm: FOUNDATION_THEME.unit[12],
        md: FOUNDATION_THEME.unit[12],
        lg: FOUNDATION_THEME.unit[12],
      },
    },
  },
  lg: {
    // background (size-independent)
    background: FOUNDATION_THEME.colors.gray[0],
    // border (size-independent)
    border: FOUNDATION_THEME.border.radius[8],
    // shadow (size-independent)
    shadow: FOUNDATION_THEME.shadows,
    // gap.[size]
    gap: {
      sm: FOUNDATION_THEME.unit[12],
      md: FOUNDATION_THEME.unit[12],
      lg: FOUNDATION_THEME.unit[12],
    },
    // zIndex (size-independent)
    zIndex: 101,
    // borderRadius.[size]
    borderRadius: {
      sm: FOUNDATION_THEME.border.radius[8],
      md: FOUNDATION_THEME.border.radius[8],
      lg: FOUNDATION_THEME.border.radius[8],
    },
    // padding.[side].[size]
    padding: {
      left: {
        sm: FOUNDATION_THEME.unit[16],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[16],
      },
      right: {
        sm: FOUNDATION_THEME.unit[16],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[16],
      },
      top: {
        sm: FOUNDATION_THEME.unit[12],
        md: FOUNDATION_THEME.unit[12],
        lg: FOUNDATION_THEME.unit[12],
      },
      bottom: {
        sm: FOUNDATION_THEME.unit[16],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[16],
      },
    },
    TopContainer: {
      gap: {
        sm: FOUNDATION_THEME.unit[8],
        md: FOUNDATION_THEME.unit[8],
        lg: FOUNDATION_THEME.unit[8],
      },
      heading: {
        // heading.fontSize.[size]
        fontSize: {
          sm: FOUNDATION_THEME.font.size.body.md.fontSize,
          md: FOUNDATION_THEME.font.size.body.lg.fontSize,
          lg: FOUNDATION_THEME.font.size.body.lg.fontSize,
        },
        // heading.fontWeight.[size]
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[600],
          md: FOUNDATION_THEME.font.weight[600],
          lg: FOUNDATION_THEME.font.weight[600],
        },
        // heading.color (size-independent)
        color: FOUNDATION_THEME.colors.gray[900],
        // heading.lineHeight.[size]
        lineHeight: {
          sm: FOUNDATION_THEME.unit[24],
          md: FOUNDATION_THEME.unit[24],
          lg: FOUNDATION_THEME.unit[24],
        },
        IconSize: {
          sm: FOUNDATION_THEME.font.fontSize[18],
          md: FOUNDATION_THEME.font.fontSize[18],
          lg: FOUNDATION_THEME.font.fontSize[18],
        },
      },
      description: {
        // description.fontSize.[size]
        fontSize: {
          sm: FOUNDATION_THEME.font.size.body.sm.fontSize,
          md: FOUNDATION_THEME.font.size.body.md.fontSize,
          lg: FOUNDATION_THEME.font.size.body.lg.fontSize,
        },
        // description.fontWeight.[size]
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        // description.color (size-independent)
        color: FOUNDATION_THEME.colors.gray[500],
        // description.lineHeight.[size]
        lineHeight: {
          sm: FOUNDATION_THEME.unit[20],
          md: FOUNDATION_THEME.unit[20],
          lg: FOUNDATION_THEME.unit[20],
        },
      },
    },
    bottomContainer: {
      // footer.gap.[size]
      gap: {
        sm: FOUNDATION_THEME.unit[12],
        md: FOUNDATION_THEME.unit[12],
        lg: FOUNDATION_THEME.unit[12],
      },
    },
  },
}
