import {
  FOUNDATION_THEME,
  ProgressBarV2Appearance,
  ProgressBarV2Size,
  type ResponsiveProgressBarV2Tokens,
} from '@juspay/blend-design-system'

/**
 * `PROGRESS_BARV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/ProgressBarV2/progressBarV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.PROGRESS_BARV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const PROGRESS_BARV2_TOKENS: ResponsiveProgressBarV2Tokens = {
  sm: {
    linear: {
      height: {
        [ProgressBarV2Size.SM]: FOUNDATION_THEME.unit[12],
        [ProgressBarV2Size.MD]: FOUNDATION_THEME.unit[20],
        [ProgressBarV2Size.LG]: FOUNDATION_THEME.unit[24],
      },
      fill: {
        backgroundColor: {
          [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.colors.primary[600]),
          [ProgressBarV2Appearance.SEGMENTED]: String(FOUNDATION_THEME.colors.primary[600]),
        },
        borderRadius: {
          [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.border.radius[8]),
          [ProgressBarV2Appearance.SEGMENTED]: String(FOUNDATION_THEME.border.radius[2]),
        },
      },
      empty: {
        backgroundColor: {
          [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.colors.gray[150]),
          [ProgressBarV2Appearance.SEGMENTED]: 'transparent',
        },
        backgroundImage: {
          [ProgressBarV2Appearance.SOLID]: undefined,
          [ProgressBarV2Appearance.SEGMENTED]: `repeating-linear-gradient(
                    to right,
                    ${String(FOUNDATION_THEME.colors.gray[100])},
                    ${String(FOUNDATION_THEME.colors.gray[100])} ${FOUNDATION_THEME.unit[2]},
                    transparent ${FOUNDATION_THEME.unit[2]},
                    transparent ${FOUNDATION_THEME.unit[8]}
                )`,
        },
        backgroundSize: {
          [ProgressBarV2Appearance.SOLID]: undefined,
          [ProgressBarV2Appearance.SEGMENTED]: `${FOUNDATION_THEME.unit[10]} 100%`,
        },
      },
      borderRadius: {
        [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.border.radius[8]),
        [ProgressBarV2Appearance.SEGMENTED]: '0px',
      },
      gap: FOUNDATION_THEME.unit[8],
    },
    circular: {
      size: {
        [ProgressBarV2Size.SM]: FOUNDATION_THEME.unit[40],
        [ProgressBarV2Size.MD]: FOUNDATION_THEME.unit[60],
        [ProgressBarV2Size.LG]: FOUNDATION_THEME.unit[80],
      },
      strokeWidth: {
        [ProgressBarV2Size.SM]: 3,
        [ProgressBarV2Size.MD]: 4,
        [ProgressBarV2Size.LG]: 6,
      },
      stroke: {
        [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.colors.primary[600]),
        [ProgressBarV2Appearance.SEGMENTED]: String(FOUNDATION_THEME.colors.primary[600]),
      },
      background: {
        [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.colors.gray[150]),
        [ProgressBarV2Appearance.SEGMENTED]: String(FOUNDATION_THEME.colors.gray[150]),
      },
      dashArray: {
        [ProgressBarV2Appearance.SOLID]: '',
        [ProgressBarV2Appearance.SEGMENTED]: '4 2',
      },
      motion: 'stroke-dashoffset 0.3s ease-in-out',
    },
    label: {
      fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
      fontWeight: FOUNDATION_THEME.font.weight[500],
      color: String(FOUNDATION_THEME.colors.gray[600]),
    },
    transition: 'width 0.3s ease-in-out',
  },
  lg: {
    linear: {
      height: {
        [ProgressBarV2Size.SM]: FOUNDATION_THEME.unit[12],
        [ProgressBarV2Size.MD]: FOUNDATION_THEME.unit[20],
        [ProgressBarV2Size.LG]: FOUNDATION_THEME.unit[24],
      },
      fill: {
        backgroundColor: {
          [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.colors.primary[600]),
          [ProgressBarV2Appearance.SEGMENTED]: String(FOUNDATION_THEME.colors.primary[600]),
        },
        borderRadius: {
          [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.border.radius[8]),
          [ProgressBarV2Appearance.SEGMENTED]: String(FOUNDATION_THEME.border.radius[2]),
        },
      },
      empty: {
        backgroundColor: {
          [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.colors.gray[150]),
          [ProgressBarV2Appearance.SEGMENTED]: 'transparent',
        },
        backgroundImage: {
          [ProgressBarV2Appearance.SOLID]: undefined,
          [ProgressBarV2Appearance.SEGMENTED]: `repeating-linear-gradient(
                    to right,
                    ${String(FOUNDATION_THEME.colors.gray[100])},
                    ${String(FOUNDATION_THEME.colors.gray[100])} ${FOUNDATION_THEME.unit[2]},
                    transparent ${FOUNDATION_THEME.unit[2]},
                    transparent ${FOUNDATION_THEME.unit[8]}
                )`,
        },
        backgroundSize: {
          [ProgressBarV2Appearance.SOLID]: undefined,
          [ProgressBarV2Appearance.SEGMENTED]: `${FOUNDATION_THEME.unit[10]} 100%`,
        },
      },
      borderRadius: {
        [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.border.radius[8]),
        [ProgressBarV2Appearance.SEGMENTED]: '0px',
      },
      gap: FOUNDATION_THEME.unit[8],
    },
    circular: {
      size: {
        [ProgressBarV2Size.SM]: FOUNDATION_THEME.unit[40],
        [ProgressBarV2Size.MD]: FOUNDATION_THEME.unit[60],
        [ProgressBarV2Size.LG]: FOUNDATION_THEME.unit[80],
      },
      strokeWidth: {
        [ProgressBarV2Size.SM]: 3,
        [ProgressBarV2Size.MD]: 4,
        [ProgressBarV2Size.LG]: 6,
      },
      stroke: {
        [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.colors.primary[600]),
        [ProgressBarV2Appearance.SEGMENTED]: String(FOUNDATION_THEME.colors.primary[600]),
      },
      background: {
        [ProgressBarV2Appearance.SOLID]: String(FOUNDATION_THEME.colors.gray[150]),
        [ProgressBarV2Appearance.SEGMENTED]: String(FOUNDATION_THEME.colors.gray[150]),
      },
      dashArray: {
        [ProgressBarV2Appearance.SOLID]: '',
        [ProgressBarV2Appearance.SEGMENTED]: '4 2',
      },
      motion: 'stroke-dashoffset 0.3s ease-in-out',
    },
    label: {
      fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
      fontWeight: FOUNDATION_THEME.font.weight[500],
      color: String(FOUNDATION_THEME.colors.gray[600]),
    },
    transition: 'width 0.3s ease-in-out',
  },
}
