import { FOUNDATION_THEME, type ResponsiveSidebarV2Tokens } from '@juspay/blend-design-system'

/**
 * `SIDEBARV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/SidebarV2/sidebarV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.SIDEBARV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const SIDEBARV2_TOKENS: ResponsiveSidebarV2Tokens = {
  sm: {
    container: {
      zIndex: FOUNDATION_THEME.zIndex[99],
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      borderRight: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      hoverPreview: {
        boxShadow: FOUNDATION_THEME.shadows['lg'],
      },
      maxWidth: {
        withLeftPanel: '300px',
        withoutLeftPanel: '250px',
        iconOnly: FOUNDATION_THEME.unit[52],
      },
    },
    leftPanel: {
      width: '52px',
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      borderRight: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      paddingTop: FOUNDATION_THEME.unit[10],
      paddingBottom: FOUNDATION_THEME.unit[10],
      paddingLeft: FOUNDATION_THEME.unit[10],
      paddingRight: FOUNDATION_THEME.unit[10],
      gap: FOUNDATION_THEME.unit[16],
      item: {
        width: FOUNDATION_THEME.unit[32],
        borderRadius: FOUNDATION_THEME.border.radius[4],
        border: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          active: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
        },
        backgroundColor: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          active: 'transparent',
        },
      },
    },
    header: {
      zIndex: FOUNDATION_THEME.zIndex[10],
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      paddingTop: FOUNDATION_THEME.unit[12],
      paddingBottom: FOUNDATION_THEME.unit[12],
      paddingLeft: FOUNDATION_THEME.unit[8],
      paddingRight: FOUNDATION_THEME.unit[8],
      gap: FOUNDATION_THEME.unit[12],
      borderBottom: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      borderBottomWidth: FOUNDATION_THEME.border.width[1],
      scrolledBorderColor: FOUNDATION_THEME.colors.gray[200],
      toggleButton: {
        borderRadius: FOUNDATION_THEME.border.radius[10],
        padding: FOUNDATION_THEME.unit[9],
        backgroundColor: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[100],
          active: FOUNDATION_THEME.colors.gray[100],
        },
        width: FOUNDATION_THEME.unit[16],
        iconColor: FOUNDATION_THEME.colors.gray[600],
      },
    },
    directory: {
      gap: FOUNDATION_THEME.unit[24],
      paddingTop: FOUNDATION_THEME.unit[12],
      paddingBottom: FOUNDATION_THEME.unit[12],
      paddingLeft: FOUNDATION_THEME.unit[12],
      paddingRight: FOUNDATION_THEME.unit[12],
    },
    footer: {
      zIndex: FOUNDATION_THEME.zIndex[10],
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      gap: FOUNDATION_THEME.unit[12],
      paddingTop: FOUNDATION_THEME.unit[12],
      paddingBottom: FOUNDATION_THEME.unit[12],
      paddingLeft: FOUNDATION_THEME.unit[8],
      paddingRight: FOUNDATION_THEME.unit[8],
      borderTop: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
    },
    primarySidebar: {
      width: '250px',
    },
    secondarySidebar: {
      width: '52px',
      borderRight: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      gap: FOUNDATION_THEME.unit[16],
      paddingTop: FOUNDATION_THEME.unit[10],
      paddingBottom: FOUNDATION_THEME.unit[10],
      paddingLeft: FOUNDATION_THEME.unit[10],
      paddingRight: FOUNDATION_THEME.unit[10],
      item: {
        width: FOUNDATION_THEME.unit[32],
        height: FOUNDATION_THEME.unit[32],
        borderRadius: FOUNDATION_THEME.border.radius[4],
        border: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          active: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
        },
        backgroundColor: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          active: 'transparent',
        },
      },
    },
  },
  lg: {
    container: {
      zIndex: FOUNDATION_THEME.zIndex[99],
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      borderRight: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      hoverPreview: {
        boxShadow: FOUNDATION_THEME.shadows['lg'],
      },
      maxWidth: {
        withLeftPanel: '320px',
        withoutLeftPanel: '270px',
        iconOnly: FOUNDATION_THEME.unit[52],
      },
    },
    leftPanel: {
      width: '52px',
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      borderRight: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      paddingTop: FOUNDATION_THEME.unit[12],
      paddingBottom: FOUNDATION_THEME.unit[12],
      paddingLeft: FOUNDATION_THEME.unit[12],
      paddingRight: FOUNDATION_THEME.unit[12],
      gap: FOUNDATION_THEME.unit[16],
      item: {
        width: FOUNDATION_THEME.unit[32],
        borderRadius: FOUNDATION_THEME.border.radius[6],
        border: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          active: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
        },
        backgroundColor: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          active: 'transparent',
        },
      },
    },
    header: {
      zIndex: FOUNDATION_THEME.zIndex[10],
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      paddingTop: FOUNDATION_THEME.unit[6],
      paddingBottom: FOUNDATION_THEME.unit[6],
      paddingLeft: FOUNDATION_THEME.unit[12],
      paddingRight: FOUNDATION_THEME.unit[12],
      gap: FOUNDATION_THEME.unit[16],
      borderBottom: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      borderBottomWidth: FOUNDATION_THEME.border.width[1],
      scrolledBorderColor: FOUNDATION_THEME.colors.gray[200],
      toggleButton: {
        borderRadius: FOUNDATION_THEME.border.radius[10],
        padding: FOUNDATION_THEME.unit[10],
        backgroundColor: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[100],
          active: FOUNDATION_THEME.colors.gray[100],
        },
        width: FOUNDATION_THEME.unit[16],
        iconColor: FOUNDATION_THEME.colors.gray[600],
      },
    },
    directory: {
      gap: FOUNDATION_THEME.unit[24],
      paddingTop: FOUNDATION_THEME.unit[12],
      paddingBottom: FOUNDATION_THEME.unit[12],
      paddingLeft: FOUNDATION_THEME.unit[12],
      paddingRight: FOUNDATION_THEME.unit[12],
    },
    footer: {
      zIndex: FOUNDATION_THEME.zIndex[10],
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      gap: FOUNDATION_THEME.unit[12],
      paddingTop: FOUNDATION_THEME.unit[16],
      paddingBottom: FOUNDATION_THEME.unit[16],
      paddingLeft: FOUNDATION_THEME.unit[12],
      paddingRight: FOUNDATION_THEME.unit[12],
      borderTop: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
    },
    primarySidebar: {
      width: '250px',
    },
    secondarySidebar: {
      width: '52px',
      borderRight: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      backgroundColor: FOUNDATION_THEME.colors.gray[25],
      gap: FOUNDATION_THEME.unit[16],
      paddingTop: FOUNDATION_THEME.unit[10],
      paddingBottom: FOUNDATION_THEME.unit[10],
      paddingLeft: FOUNDATION_THEME.unit[10],
      paddingRight: FOUNDATION_THEME.unit[10],
      item: {
        width: FOUNDATION_THEME.unit[32],
        height: FOUNDATION_THEME.unit[32],
        borderRadius: FOUNDATION_THEME.border.radius[4],
        border: {
          default: `1px solid ${FOUNDATION_THEME.colors.gray[150]}`,
          hover: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
          active: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
        },
        backgroundColor: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          active: 'transparent',
        },
      },
    },
  },
}
