import {
  FOUNDATION_THEME,
  SingleSelectV2Size,
  SingleSelectV2Variant,
  type ResponsiveSingleSelectV2Tokens,
} from '@juspay/blend-design-system'

/**
 * `SINGLE_SELECT_V2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/SingleSelectV2/singleSelectV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.SINGLE_SELECT_V2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
const createBaseTokens = (): ResponsiveSingleSelectV2Tokens['sm'] => ({
  gap: FOUNDATION_THEME.unit[8],
  label: {
    fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
    fontWeight: FOUNDATION_THEME.font.weight[500],
    color: {
      default: FOUNDATION_THEME.colors.gray[700],
      hover: FOUNDATION_THEME.colors.gray[700],
      active: FOUNDATION_THEME.colors.gray[700],
      focus: FOUNDATION_THEME.colors.gray[700],
      focusVisible: FOUNDATION_THEME.colors.gray[700],
      disabled: FOUNDATION_THEME.colors.gray[400],
      selected: FOUNDATION_THEME.colors.gray[700],
    },
  },
  subLabel: {
    fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
    fontWeight: FOUNDATION_THEME.font.weight[400],
    color: {
      default: FOUNDATION_THEME.colors.gray[400],
      hover: FOUNDATION_THEME.colors.gray[400],
      active: FOUNDATION_THEME.colors.gray[400],
      focus: FOUNDATION_THEME.colors.gray[400],
      focusVisible: FOUNDATION_THEME.colors.gray[400],
      disabled: FOUNDATION_THEME.colors.gray[300],
      selected: FOUNDATION_THEME.colors.gray[400],
    },
  },
  hintText: {
    fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
    fontWeight: FOUNDATION_THEME.font.weight[400],
    color: {
      default: FOUNDATION_THEME.colors.gray[500],
      hover: FOUNDATION_THEME.colors.gray[500],
      active: FOUNDATION_THEME.colors.gray[500],
      focus: FOUNDATION_THEME.colors.gray[500],
      focusVisible: FOUNDATION_THEME.colors.gray[500],
      disabled: FOUNDATION_THEME.colors.gray[400],
      selected: FOUNDATION_THEME.colors.gray[500],
    },
  },
  errorMessage: {
    fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
    fontWeight: FOUNDATION_THEME.font.weight[500],
    color: FOUNDATION_THEME.colors.red[600],
  },
  required: { color: FOUNDATION_THEME.colors.red[600] },

  trigger: {
    height: {
      [SingleSelectV2Size.SM]: {
        [SingleSelectV2Variant.CONTAINER]: FOUNDATION_THEME.unit[32],
        [SingleSelectV2Variant.NO_CONTAINER]: FOUNDATION_THEME.unit[32],
      },
      [SingleSelectV2Size.MD]: {
        [SingleSelectV2Variant.CONTAINER]: FOUNDATION_THEME.unit[36],
        [SingleSelectV2Variant.NO_CONTAINER]: FOUNDATION_THEME.unit[36],
      },
      [SingleSelectV2Size.LG]: {
        [SingleSelectV2Variant.CONTAINER]: FOUNDATION_THEME.unit[40],
        [SingleSelectV2Variant.NO_CONTAINER]: FOUNDATION_THEME.unit[40],
      },
    },
    padding: {
      [SingleSelectV2Size.SM]: {
        [SingleSelectV2Variant.CONTAINER]: {
          top: FOUNDATION_THEME.unit[7],
          right: FOUNDATION_THEME.unit[14],
          bottom: FOUNDATION_THEME.unit[7],
          left: FOUNDATION_THEME.unit[14],
        },
        [SingleSelectV2Variant.NO_CONTAINER]: {
          top: FOUNDATION_THEME.unit[7],
          right: FOUNDATION_THEME.unit[14],
          bottom: FOUNDATION_THEME.unit[7],
          left: FOUNDATION_THEME.unit[14],
        },
      },
      [SingleSelectV2Size.MD]: {
        [SingleSelectV2Variant.CONTAINER]: {
          top: FOUNDATION_THEME.unit[8],
          right: FOUNDATION_THEME.unit[14],
          bottom: FOUNDATION_THEME.unit[8],
          left: FOUNDATION_THEME.unit[14],
        },
        [SingleSelectV2Variant.NO_CONTAINER]: {
          top: FOUNDATION_THEME.unit[8],
          right: FOUNDATION_THEME.unit[14],
          bottom: FOUNDATION_THEME.unit[8],
          left: FOUNDATION_THEME.unit[14],
        },
      },
      [SingleSelectV2Size.LG]: {
        [SingleSelectV2Variant.CONTAINER]: {
          top: FOUNDATION_THEME.unit[10],
          right: FOUNDATION_THEME.unit[12],
          bottom: FOUNDATION_THEME.unit[10],
          left: FOUNDATION_THEME.unit[12],
        },
        [SingleSelectV2Variant.NO_CONTAINER]: {
          top: FOUNDATION_THEME.unit[10],
          right: FOUNDATION_THEME.unit[12],
          bottom: FOUNDATION_THEME.unit[10],
          left: FOUNDATION_THEME.unit[12],
        },
      },
    },
    borderRadius: {
      [SingleSelectV2Size.SM]: {
        [SingleSelectV2Variant.CONTAINER]: FOUNDATION_THEME.unit[10],
        [SingleSelectV2Variant.NO_CONTAINER]: FOUNDATION_THEME.unit[10],
      },
      [SingleSelectV2Size.MD]: {
        [SingleSelectV2Variant.CONTAINER]: FOUNDATION_THEME.unit[10],
        [SingleSelectV2Variant.NO_CONTAINER]: FOUNDATION_THEME.unit[10],
      },
      [SingleSelectV2Size.LG]: {
        [SingleSelectV2Variant.CONTAINER]: FOUNDATION_THEME.unit[10],
        [SingleSelectV2Variant.NO_CONTAINER]: FOUNDATION_THEME.unit[10],
      },
    },
    boxShadow: {
      [SingleSelectV2Variant.CONTAINER]: FOUNDATION_THEME.shadows.xs,
      [SingleSelectV2Variant.NO_CONTAINER]: 'none',
    },
    slot: {
      gap: FOUNDATION_THEME.unit[8],
      width: FOUNDATION_THEME.unit[20],
    },
    backgroundColor: {
      [SingleSelectV2Variant.CONTAINER]: {
        open: FOUNDATION_THEME.colors.gray[25],
        closed: FOUNDATION_THEME.colors.gray[0],
        hover: FOUNDATION_THEME.colors.gray[50],
        focus: FOUNDATION_THEME.colors.gray[50],
        error: FOUNDATION_THEME.colors.gray[0],
      },
      [SingleSelectV2Variant.NO_CONTAINER]: {
        open: 'transparent',
        closed: 'transparent',
        hover: FOUNDATION_THEME.colors.gray[50],
        focus: FOUNDATION_THEME.colors.gray[50],
        error: 'transparent',
      },
    },
    outline: {
      [SingleSelectV2Variant.CONTAINER]: {
        open: `1px solid ${FOUNDATION_THEME.colors.gray[200]} !important`,
        closed: `1px solid ${FOUNDATION_THEME.colors.gray[200]} !important`,
        hover: `1px solid ${FOUNDATION_THEME.colors.gray[200]} !important`,
        focus: `1px solid ${FOUNDATION_THEME.colors.gray[200]} !important`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]} !important`,
      },
      [SingleSelectV2Variant.NO_CONTAINER]: {
        open: undefined,
        closed: undefined,
        hover: undefined,
        focus: undefined,
        error: undefined,
      },
    },
    placeholder: {
      color: FOUNDATION_THEME.colors.gray[400],
      fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
      fontWeight: FOUNDATION_THEME.font.weight[500],
    },
    selectedValue: {
      color: FOUNDATION_THEME.colors.gray[700],
      fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
      fontWeight: FOUNDATION_THEME.font.weight[500],
    },
  },

  menu: {
    content: {
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
      border: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      borderRadius: FOUNDATION_THEME.unit[8],
      boxShadow: FOUNDATION_THEME.shadows.sm,
    },
    padding: {
      [SingleSelectV2Size.SM]: {
        [SingleSelectV2Variant.CONTAINER]: {
          top: FOUNDATION_THEME.unit[6],
          right: FOUNDATION_THEME.unit[6],
          bottom: FOUNDATION_THEME.unit[6],
          left: FOUNDATION_THEME.unit[6],
        },
        [SingleSelectV2Variant.NO_CONTAINER]: {
          top: FOUNDATION_THEME.unit[6],
          right: FOUNDATION_THEME.unit[6],
          bottom: FOUNDATION_THEME.unit[6],
          left: FOUNDATION_THEME.unit[6],
        },
      },
      [SingleSelectV2Size.MD]: {
        [SingleSelectV2Variant.CONTAINER]: {
          top: FOUNDATION_THEME.unit[6],
          right: FOUNDATION_THEME.unit[6],
          bottom: FOUNDATION_THEME.unit[6],
          left: FOUNDATION_THEME.unit[6],
        },
        [SingleSelectV2Variant.NO_CONTAINER]: {
          top: FOUNDATION_THEME.unit[6],
          right: FOUNDATION_THEME.unit[6],
          bottom: FOUNDATION_THEME.unit[6],
          left: FOUNDATION_THEME.unit[6],
        },
      },
      [SingleSelectV2Size.LG]: {
        [SingleSelectV2Variant.CONTAINER]: {
          top: FOUNDATION_THEME.unit[6],
          right: FOUNDATION_THEME.unit[6],
          bottom: FOUNDATION_THEME.unit[6],
          left: FOUNDATION_THEME.unit[6],
        },
        [SingleSelectV2Variant.NO_CONTAINER]: {
          top: FOUNDATION_THEME.unit[6],
          right: FOUNDATION_THEME.unit[6],
          bottom: FOUNDATION_THEME.unit[6],
          left: FOUNDATION_THEME.unit[6],
        },
      },
    },
    groupLabel: {
      margin: '0',
      paddingTop: FOUNDATION_THEME.unit[8],
      paddingRight: FOUNDATION_THEME.unit[6],
      paddingBottom: FOUNDATION_THEME.unit[8],
      paddingLeft: FOUNDATION_THEME.unit[6],
      fontSize: FOUNDATION_THEME.font.size.body.sm.fontSize,
      fontWeight: FOUNDATION_THEME.font.weight[400],
      color: {
        default: FOUNDATION_THEME.colors.gray[400],
        hover: FOUNDATION_THEME.colors.gray[400],
        active: FOUNDATION_THEME.colors.gray[400],
        focus: FOUNDATION_THEME.colors.gray[400],
        focusVisible: FOUNDATION_THEME.colors.gray[400],
        disabled: FOUNDATION_THEME.colors.gray[400],
        selected: FOUNDATION_THEME.colors.gray[400],
      },
    },
    item: {
      paddingTop: FOUNDATION_THEME.unit[6],
      paddingRight: FOUNDATION_THEME.unit[8],
      paddingBottom: FOUNDATION_THEME.unit[6],
      paddingLeft: FOUNDATION_THEME.unit[8],
      margin: `${FOUNDATION_THEME.unit[0]} ${FOUNDATION_THEME.unit[4]}`,
      borderRadius: FOUNDATION_THEME.unit[8],
      gap: FOUNDATION_THEME.unit[4],
      backgroundColor: {
        default: FOUNDATION_THEME.colors.gray[0],
        hover: FOUNDATION_THEME.colors.gray[50],
        active: FOUNDATION_THEME.colors.gray[100],
        focus: FOUNDATION_THEME.colors.gray[100],
        focusVisible: FOUNDATION_THEME.colors.gray[100],
        disabled: FOUNDATION_THEME.colors.gray[50],
        selected: FOUNDATION_THEME.colors.gray[50],
      },
      groupLabelText: {
        fontSize: FOUNDATION_THEME.font.size.body.sm.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[400],
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[400],
          active: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[400],
          focusVisible: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[400],
          selected: FOUNDATION_THEME.colors.gray[400],
        },
      },
      option: {
        fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[500],
        color: {
          default: FOUNDATION_THEME.colors.gray[600],
          hover: FOUNDATION_THEME.colors.gray[700],
          active: FOUNDATION_THEME.colors.gray[700],
          focus: FOUNDATION_THEME.colors.gray[700],
          focusVisible: FOUNDATION_THEME.colors.gray[700],
          disabled: FOUNDATION_THEME.colors.gray[400],
          selected: FOUNDATION_THEME.colors.gray[700],
        },
      },
      description: {
        fontSize: FOUNDATION_THEME.font.size.body.sm.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[400],
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[400],
          active: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[400],
          focusVisible: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[100],
          selected: FOUNDATION_THEME.colors.gray[400],
        },
      },
      separator: {
        color: FOUNDATION_THEME.colors.gray[200],
        height: 1,
        margin: `${FOUNDATION_THEME.unit[6]} 0`,
      },
    },
    submenu: {
      trigger: {
        paddingTop: FOUNDATION_THEME.unit[8],
        paddingRight: FOUNDATION_THEME.unit[6],
        paddingBottom: FOUNDATION_THEME.unit[8],
        paddingLeft: FOUNDATION_THEME.unit[6],
        margin: `0 ${FOUNDATION_THEME.unit[8]}`,
        borderRadius: FOUNDATION_THEME.unit[4],
        backgroundColor: {
          default: 'transparent',
          hover: FOUNDATION_THEME.colors.gray[50],
          focus: FOUNDATION_THEME.colors.gray[50],
        },
      },
      content: {
        backgroundColor: FOUNDATION_THEME.colors.gray[0],
        border: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        borderRadius: FOUNDATION_THEME.unit[8],
        paddingTop: FOUNDATION_THEME.unit[6],
        paddingRight: FOUNDATION_THEME.unit[6],
        paddingBottom: FOUNDATION_THEME.unit[6],
        paddingLeft: FOUNDATION_THEME.unit[6],
        boxShadow: FOUNDATION_THEME.shadows.lg,
      },
      optionText: {
        fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[500],
        color: FOUNDATION_THEME.colors.gray[600],
      },
      iconColor: FOUNDATION_THEME.colors.gray[400],
    },
    footer: {
      paddingTop: FOUNDATION_THEME.unit[16],
      paddingRight: FOUNDATION_THEME.unit[16],
      paddingBottom: FOUNDATION_THEME.unit[16],
      paddingLeft: FOUNDATION_THEME.unit[16],
      backgroundColor: FOUNDATION_THEME.colors.gray[0],
      borderTop: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
    },
  },

  mobilePanel: {
    header: {
      paddingTop: FOUNDATION_THEME.unit[0],
      paddingRight: FOUNDATION_THEME.unit[16],
      paddingBottom: FOUNDATION_THEME.unit[12],
      paddingLeft: FOUNDATION_THEME.unit[16],
      borderBottom: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
    },
  },
})

const baseTokens = createBaseTokens()

export const SINGLE_SELECT_V2_TOKENS: ResponsiveSingleSelectV2Tokens = {
  sm: baseTokens,
  lg: baseTokens,
}
