import { FOUNDATION_THEME, type ResponsiveSwitchV2Tokens } from '@juspay/blend-design-system'

/**
 * `SWITCHV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/SelectorV2/SwitchV2/switchV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.SWITCHV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const SWITCHV2_TOKENS: ResponsiveSwitchV2Tokens = {
  sm: {
    gap: FOUNDATION_THEME.unit[8],
    switch: {
      height: {
        sm: FOUNDATION_THEME.unit[12],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[16],
      },
      width: {
        sm: FOUNDATION_THEME.unit[24],
        md: FOUNDATION_THEME.unit[32],
        lg: FOUNDATION_THEME.unit[32],
      },
      backgroundColor: {
        checked: {
          default: FOUNDATION_THEME.colors.primary[500],
          hover: FOUNDATION_THEME.colors.primary[600],
          disabled: FOUNDATION_THEME.colors.primary[200],
          error: FOUNDATION_THEME.colors.red[500],
          focus: FOUNDATION_THEME.colors.primary[600],
        },
        unchecked: {
          default: FOUNDATION_THEME.colors.gray[200],
          hover: FOUNDATION_THEME.colors.gray[300],
          disabled: FOUNDATION_THEME.colors.gray[100],
          error: FOUNDATION_THEME.colors.gray[200],
          focus: FOUNDATION_THEME.colors.gray[300],
        },
      },

      thumb: {
        backgroundColor: FOUNDATION_THEME.colors.gray[0],
        border: `0.5px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        width: {
          sm: FOUNDATION_THEME.unit[10],
          md: FOUNDATION_THEME.unit[14],
          lg: FOUNDATION_THEME.unit[14],
        },
        height: {
          sm: FOUNDATION_THEME.unit[10],
          md: FOUNDATION_THEME.unit[14],
          lg: FOUNDATION_THEME.unit[14],
        },
        outline: `1px solid ${FOUNDATION_THEME.colors.primary[200]}`,
      },
    },
    content: {
      gap: FOUNDATION_THEME.unit[6],
      label: {
        gap: FOUNDATION_THEME.unit[6],
        color: {
          default: FOUNDATION_THEME.colors.gray[700],
          hover: FOUNDATION_THEME.colors.gray[800],
          disabled: FOUNDATION_THEME.colors.gray[300],
          error: FOUNDATION_THEME.colors.red[600],
          focus: FOUNDATION_THEME.colors.gray[800],
        },
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[12],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[12],
          md: FOUNDATION_THEME.font.lineHeight[16],
          lg: FOUNDATION_THEME.font.lineHeight[16],
        },
        slot: {
          maxHeight: {
            sm: FOUNDATION_THEME.unit[12],
            md: FOUNDATION_THEME.unit[14],
            lg: FOUNDATION_THEME.unit[14],
          },
        },
      },
      subLabel: {
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[500],
          disabled: FOUNDATION_THEME.colors.gray[200],
          error: FOUNDATION_THEME.colors.red[500],
          focus: FOUNDATION_THEME.colors.gray[500],
        },
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[12],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[400],
          md: FOUNDATION_THEME.font.weight[400],
          lg: FOUNDATION_THEME.font.weight[400],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[12],
          md: FOUNDATION_THEME.font.lineHeight[16],
          lg: FOUNDATION_THEME.font.lineHeight[16],
        },
      },
      required: {
        color: FOUNDATION_THEME.colors.red[600],
      },
    },
  },
  lg: {
    gap: FOUNDATION_THEME.unit[8],

    switch: {
      height: {
        sm: FOUNDATION_THEME.unit[12],
        md: FOUNDATION_THEME.unit[16],
        lg: FOUNDATION_THEME.unit[16],
      },
      width: {
        sm: FOUNDATION_THEME.unit[24],
        md: FOUNDATION_THEME.unit[32],
        lg: FOUNDATION_THEME.unit[32],
      },
      backgroundColor: {
        checked: {
          default: FOUNDATION_THEME.colors.primary[600],
          hover: FOUNDATION_THEME.colors.primary[600],
          disabled: FOUNDATION_THEME.colors.primary[200],
          error: FOUNDATION_THEME.colors.red[500],
          focus: FOUNDATION_THEME.colors.primary[600],
        },
        unchecked: {
          default: FOUNDATION_THEME.colors.gray[200],
          hover: FOUNDATION_THEME.colors.gray[300],
          disabled: FOUNDATION_THEME.colors.gray[100],
          error: FOUNDATION_THEME.colors.gray[200],
          focus: FOUNDATION_THEME.colors.gray[300],
        },
      },

      thumb: {
        backgroundColor: FOUNDATION_THEME.colors.gray[0],
        border: `0.5px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        width: {
          sm: FOUNDATION_THEME.unit[10],
          md: FOUNDATION_THEME.unit[14],
          lg: FOUNDATION_THEME.unit[14],
        },
        height: {
          sm: FOUNDATION_THEME.unit[10],
          md: FOUNDATION_THEME.unit[14],
          lg: FOUNDATION_THEME.unit[14],
        },
        outline: `1px solid ${FOUNDATION_THEME.colors.primary[200]}`,
      },
    },

    content: {
      gap: FOUNDATION_THEME.unit[6],
      label: {
        gap: FOUNDATION_THEME.unit[6],
        color: {
          default: FOUNDATION_THEME.colors.gray[700],
          hover: FOUNDATION_THEME.colors.gray[800],
          disabled: FOUNDATION_THEME.colors.gray[300],
          error: FOUNDATION_THEME.colors.red[600],
          focus: FOUNDATION_THEME.colors.gray[800],
        },
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[12],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[12],
          md: FOUNDATION_THEME.font.lineHeight[16],
          lg: FOUNDATION_THEME.font.lineHeight[16],
        },
        slot: {
          maxHeight: {
            sm: FOUNDATION_THEME.unit[12],
            md: FOUNDATION_THEME.unit[14],
            lg: FOUNDATION_THEME.unit[14],
          },
        },
      },

      subLabel: {
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[500],
          disabled: FOUNDATION_THEME.colors.gray[200],
          error: FOUNDATION_THEME.colors.red[500],
          focus: FOUNDATION_THEME.colors.gray[500],
        },
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[12],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[400],
          md: FOUNDATION_THEME.font.weight[400],
          lg: FOUNDATION_THEME.font.weight[400],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[12],
          md: FOUNDATION_THEME.font.lineHeight[16],
          lg: FOUNDATION_THEME.font.lineHeight[16],
        },
      },
      required: {
        color: FOUNDATION_THEME.colors.red[600],
      },
    },
  },
}
