import {
  FOUNDATION_THEME,
  TabsV2Size,
  TabsV2Variant,
  type ResponsiveTabsV2Tokens,
} from '@juspay/blend-design-system'

/**
 * `TABSV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/TabsV2/tabsV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.TABSV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const TABSV2_TOKENS: ResponsiveTabsV2Tokens = {
  sm: {
    width: '100%',
    outline: 'none',
    tabList: {
      gap: FOUNDATION_THEME.unit[8],
      backgroundColor: {
        [TabsV2Variant.UNDERLINE]: 'transparent',
        [TabsV2Variant.BOXED]: FOUNDATION_THEME.colors.gray[50],
        [TabsV2Variant.FLOATING]: 'transparent',
        [TabsV2Variant.PILLS]: 'transparent',
      },
      borderRadius: {
        [TabsV2Size.SM]: {
          [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
          [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[0],
        },
        [TabsV2Size.MD]: {
          [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
          [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[0],
        },
        [TabsV2Size.LG]: {
          [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
          [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[0],
        },
      },
      padding: {
        [TabsV2Size.SM]: {
          [TabsV2Variant.UNDERLINE]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[0],
            bottom: FOUNDATION_THEME.unit[0],
            left: FOUNDATION_THEME.unit[0],
          },
          [TabsV2Variant.BOXED]: {
            top: FOUNDATION_THEME.unit[2],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[2],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.FLOATING]: {
            top: FOUNDATION_THEME.unit[2],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[2],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.PILLS]: {
            top: FOUNDATION_THEME.unit[2],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[2],
            left: FOUNDATION_THEME.unit[4],
          },
        },
        [TabsV2Size.MD]: {
          [TabsV2Variant.UNDERLINE]: {
            top: FOUNDATION_THEME.unit[8],
            right: FOUNDATION_THEME.unit[0],
            bottom: FOUNDATION_THEME.unit[0],
            left: FOUNDATION_THEME.unit[0],
          },
          [TabsV2Variant.BOXED]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.FLOATING]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.PILLS]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
        },
        [TabsV2Size.LG]: {
          [TabsV2Variant.UNDERLINE]: {
            top: FOUNDATION_THEME.unit[8],
            right: FOUNDATION_THEME.unit[0],
            bottom: FOUNDATION_THEME.unit[0],
            left: FOUNDATION_THEME.unit[0],
          },
          [TabsV2Variant.BOXED]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.FLOATING]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.PILLS]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
        },
      },
      borderBottom: {
        [TabsV2Variant.UNDERLINE]: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
        [TabsV2Variant.BOXED]: 'none',
        [TabsV2Variant.FLOATING]: 'none',
        [TabsV2Variant.PILLS]: 'none',
      },
      activeIndicator: {
        height: FOUNDATION_THEME.border.width[2],
        color: FOUNDATION_THEME.colors.gray[700],
        position: {
          bottom: FOUNDATION_THEME.unit[0],
        },
        transition:
          'scale 250ms cubic-bezier(0.4, 0, 0.2, 1), translate 250ms cubic-bezier(0.4, 0, 0.2, 1)',
        zIndex: 2,
      },
      stickyHeader: {
        boxShadow: FOUNDATION_THEME.shadows.xs,
        zIndex: 50,
      },
      trigger: {
        gap: FOUNDATION_THEME.unit[8],
        icon: {
          maxWidth: FOUNDATION_THEME.unit[20],
        },
        backgroundColor: {
          [TabsV2Variant.UNDERLINE]: {
            default: 'transparent',
            hover: 'transparent',
            active: 'transparent',
            disabled: 'transparent',
          },
          [TabsV2Variant.BOXED]: {
            default: 'transparent',
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: 'transparent',
          },
          [TabsV2Variant.FLOATING]: {
            default: 'transparent',
            hover: FOUNDATION_THEME.colors.gray[50],
            active: FOUNDATION_THEME.colors.gray[100],
            disabled: 'transparent',
          },
          [TabsV2Variant.PILLS]: {
            default: 'transparent',
            hover: FOUNDATION_THEME.colors.gray[50],
            active: FOUNDATION_THEME.colors.gray[100],
            disabled: 'transparent',
          },
        },
        borderRadius: {
          [TabsV2Size.SM]: {
            [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
            [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[28],
          },
          [TabsV2Size.MD]: {
            [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
            [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[28],
          },
          [TabsV2Size.LG]: {
            [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
            [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[28],
          },
        },
        border: {
          [TabsV2Variant.UNDERLINE]: 'none',
          [TabsV2Variant.BOXED]: 'none',
          [TabsV2Variant.FLOATING]: 'none',
          [TabsV2Variant.PILLS]: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
        },
        padding: {
          [TabsV2Size.SM]: {
            [TabsV2Variant.UNDERLINE]: {
              top: FOUNDATION_THEME.unit[2],
              right: FOUNDATION_THEME.unit[8],
              bottom: FOUNDATION_THEME.unit[8],
              left: FOUNDATION_THEME.unit[8],
            },
            [TabsV2Variant.BOXED]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.FLOATING]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.PILLS]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[12],
            },
          },
          [TabsV2Size.MD]: {
            [TabsV2Variant.UNDERLINE]: {
              top: FOUNDATION_THEME.unit[2],
              right: FOUNDATION_THEME.unit[8],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[8],
            },
            [TabsV2Variant.BOXED]: {
              top: FOUNDATION_THEME.unit[8],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[8],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.FLOATING]: {
              top: FOUNDATION_THEME.unit[8],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[8],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.PILLS]: {
              top: FOUNDATION_THEME.unit[4],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[4],
              left: FOUNDATION_THEME.unit[12],
            },
          },
          [TabsV2Size.LG]: {
            [TabsV2Variant.UNDERLINE]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[8],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[8],
            },
            [TabsV2Variant.BOXED]: {
              top: FOUNDATION_THEME.unit[10],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[10],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.FLOATING]: {
              top: FOUNDATION_THEME.unit[10],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[10],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.PILLS]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[12],
            },
          },
        },
        text: {
          color: {
            [TabsV2Variant.UNDERLINE]: {
              default: FOUNDATION_THEME.colors.gray[500],
              hover: FOUNDATION_THEME.colors.gray[500],
              active: FOUNDATION_THEME.colors.gray[700],
              disabled: FOUNDATION_THEME.colors.gray[400],
            },
            [TabsV2Variant.BOXED]: {
              default: FOUNDATION_THEME.colors.gray[500],
              hover: FOUNDATION_THEME.colors.gray[500],
              active: FOUNDATION_THEME.colors.gray[700],
              disabled: FOUNDATION_THEME.colors.gray[400],
            },
            [TabsV2Variant.FLOATING]: {
              default: FOUNDATION_THEME.colors.gray[500],
              hover: FOUNDATION_THEME.colors.gray[700],
              active: FOUNDATION_THEME.colors.gray[700],
              disabled: FOUNDATION_THEME.colors.gray[400],
            },
            [TabsV2Variant.PILLS]: {
              default: FOUNDATION_THEME.colors.gray[500],
              hover: FOUNDATION_THEME.colors.gray[700],
              active: FOUNDATION_THEME.colors.gray[700],
              disabled: FOUNDATION_THEME.colors.gray[400],
            },
          },
          fontSize: {
            [TabsV2Size.SM]: FOUNDATION_THEME.font.size.body.md.fontSize,
            [TabsV2Size.MD]: FOUNDATION_THEME.font.size.body.md.fontSize,
            [TabsV2Size.LG]: FOUNDATION_THEME.font.size.body.md.fontSize,
          },
          fontWeight: {
            [TabsV2Size.SM]: FOUNDATION_THEME.font.weight[500],
            [TabsV2Size.MD]: FOUNDATION_THEME.font.weight[500],
            [TabsV2Size.LG]: FOUNDATION_THEME.font.weight[500],
          },
        },
        closeButton: {
          width: FOUNDATION_THEME.unit[16],
          borderRadius: FOUNDATION_THEME.border.radius.full,
          backgroundColor: {
            default: 'transparent',
            hover: FOUNDATION_THEME.colors.gray[100],
            active: FOUNDATION_THEME.colors.gray[150],
            disabled: 'transparent',
          },
        },
        transition: 'color 0.2s ease-in-out',
      },
    },
  },
  lg: {
    width: '100%',
    outline: 'none',
    tabList: {
      gap: FOUNDATION_THEME.unit[8],
      backgroundColor: {
        [TabsV2Variant.UNDERLINE]: 'transparent',
        [TabsV2Variant.BOXED]: FOUNDATION_THEME.colors.gray[50],
        [TabsV2Variant.FLOATING]: 'transparent',
        [TabsV2Variant.PILLS]: 'transparent',
      },
      borderRadius: {
        [TabsV2Size.SM]: {
          [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
          [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[0],
        },
        [TabsV2Size.MD]: {
          [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
          [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[0],
        },
        [TabsV2Size.LG]: {
          [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
          [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[0],
          [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[0],
        },
      },
      padding: {
        [TabsV2Size.SM]: {
          [TabsV2Variant.UNDERLINE]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[0],
            bottom: FOUNDATION_THEME.unit[0],
            left: FOUNDATION_THEME.unit[0],
          },
          [TabsV2Variant.BOXED]: {
            top: FOUNDATION_THEME.unit[2],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[2],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.FLOATING]: {
            top: FOUNDATION_THEME.unit[2],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[2],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.PILLS]: {
            top: FOUNDATION_THEME.unit[2],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[2],
            left: FOUNDATION_THEME.unit[4],
          },
        },
        [TabsV2Size.MD]: {
          [TabsV2Variant.UNDERLINE]: {
            top: FOUNDATION_THEME.unit[8],
            right: FOUNDATION_THEME.unit[0],
            bottom: FOUNDATION_THEME.unit[0],
            left: FOUNDATION_THEME.unit[0],
          },
          [TabsV2Variant.BOXED]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.FLOATING]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.PILLS]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
        },
        [TabsV2Size.LG]: {
          [TabsV2Variant.UNDERLINE]: {
            top: FOUNDATION_THEME.unit[8],
            right: FOUNDATION_THEME.unit[0],
            bottom: FOUNDATION_THEME.unit[0],
            left: FOUNDATION_THEME.unit[0],
          },
          [TabsV2Variant.BOXED]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.FLOATING]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
          [TabsV2Variant.PILLS]: {
            top: FOUNDATION_THEME.unit[4],
            right: FOUNDATION_THEME.unit[4],
            bottom: FOUNDATION_THEME.unit[4],
            left: FOUNDATION_THEME.unit[4],
          },
        },
      },
      borderBottom: {
        [TabsV2Variant.UNDERLINE]: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
        [TabsV2Variant.BOXED]: 'none',
        [TabsV2Variant.FLOATING]: 'none',
        [TabsV2Variant.PILLS]: 'none',
      },
      activeIndicator: {
        height: FOUNDATION_THEME.border.width[2],
        color: FOUNDATION_THEME.colors.gray[700],
        position: {
          bottom: FOUNDATION_THEME.unit[0],
        },
        transition:
          'scale 250ms cubic-bezier(0.4, 0, 0.2, 1), translate 250ms cubic-bezier(0.4, 0, 0.2, 1)',
        zIndex: 2,
      },
      stickyHeader: {
        boxShadow: FOUNDATION_THEME.shadows.xs,
        zIndex: 50,
      },
      trigger: {
        gap: FOUNDATION_THEME.unit[8],
        icon: {
          maxWidth: FOUNDATION_THEME.unit[20],
        },
        backgroundColor: {
          [TabsV2Variant.UNDERLINE]: {
            default: 'transparent',
            hover: 'transparent',
            active: 'transparent',
            disabled: 'transparent',
          },
          [TabsV2Variant.BOXED]: {
            default: 'transparent',
            hover: FOUNDATION_THEME.colors.gray[0],
            active: FOUNDATION_THEME.colors.gray[0],
            disabled: 'transparent',
          },
          [TabsV2Variant.FLOATING]: {
            default: 'transparent',
            hover: FOUNDATION_THEME.colors.gray[50],
            active: FOUNDATION_THEME.colors.gray[100],
            disabled: 'transparent',
          },
          [TabsV2Variant.PILLS]: {
            default: 'transparent',
            hover: FOUNDATION_THEME.colors.gray[50],
            active: FOUNDATION_THEME.colors.gray[100],
            disabled: 'transparent',
          },
        },
        borderRadius: {
          [TabsV2Size.SM]: {
            [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
            [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[28],
          },
          [TabsV2Size.MD]: {
            [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
            [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[28],
          },
          [TabsV2Size.LG]: {
            [TabsV2Variant.UNDERLINE]: FOUNDATION_THEME.border.radius[0],
            [TabsV2Variant.BOXED]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.FLOATING]: FOUNDATION_THEME.border.radius[8],
            [TabsV2Variant.PILLS]: FOUNDATION_THEME.border.radius[28],
          },
        },
        border: {
          [TabsV2Variant.UNDERLINE]: 'none',
          [TabsV2Variant.BOXED]: 'none',
          [TabsV2Variant.FLOATING]: 'none',
          [TabsV2Variant.PILLS]: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
        },
        padding: {
          [TabsV2Size.SM]: {
            [TabsV2Variant.UNDERLINE]: {
              top: FOUNDATION_THEME.unit[2],
              right: FOUNDATION_THEME.unit[8],
              bottom: FOUNDATION_THEME.unit[8],
              left: FOUNDATION_THEME.unit[8],
            },
            [TabsV2Variant.BOXED]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.FLOATING]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.PILLS]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[6],
              left: FOUNDATION_THEME.unit[12],
            },
          },
          [TabsV2Size.MD]: {
            [TabsV2Variant.UNDERLINE]: {
              top: FOUNDATION_THEME.unit[2],
              right: FOUNDATION_THEME.unit[8],
              bottom: FOUNDATION_THEME.unit[12],
              left: FOUNDATION_THEME.unit[8],
            },
            [TabsV2Variant.BOXED]: {
              top: FOUNDATION_THEME.unit[8],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[8],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.FLOATING]: {
              top: FOUNDATION_THEME.unit[8],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[8],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.PILLS]: {
              top: FOUNDATION_THEME.unit[8],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[8],
              left: FOUNDATION_THEME.unit[12],
            },
          },
          [TabsV2Size.LG]: {
            [TabsV2Variant.UNDERLINE]: {
              top: FOUNDATION_THEME.unit[6],
              right: FOUNDATION_THEME.unit[8],
              bottom: FOUNDATION_THEME.unit[12],
              left: FOUNDATION_THEME.unit[8],
            },
            [TabsV2Variant.BOXED]: {
              top: FOUNDATION_THEME.unit[10],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[10],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.FLOATING]: {
              top: FOUNDATION_THEME.unit[10],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[10],
              left: FOUNDATION_THEME.unit[12],
            },
            [TabsV2Variant.PILLS]: {
              top: FOUNDATION_THEME.unit[10],
              right: FOUNDATION_THEME.unit[12],
              bottom: FOUNDATION_THEME.unit[10],
              left: FOUNDATION_THEME.unit[12],
            },
          },
        },
        text: {
          color: {
            [TabsV2Variant.UNDERLINE]: {
              default: FOUNDATION_THEME.colors.gray[500],
              hover: FOUNDATION_THEME.colors.gray[500],
              active: FOUNDATION_THEME.colors.gray[700],
              disabled: FOUNDATION_THEME.colors.gray[400],
            },
            [TabsV2Variant.BOXED]: {
              default: FOUNDATION_THEME.colors.gray[500],
              hover: FOUNDATION_THEME.colors.gray[500],
              active: FOUNDATION_THEME.colors.gray[700],
              disabled: FOUNDATION_THEME.colors.gray[400],
            },
            [TabsV2Variant.FLOATING]: {
              default: FOUNDATION_THEME.colors.gray[500],
              hover: FOUNDATION_THEME.colors.gray[700],
              active: FOUNDATION_THEME.colors.gray[700],
              disabled: FOUNDATION_THEME.colors.gray[400],
            },
            [TabsV2Variant.PILLS]: {
              default: FOUNDATION_THEME.colors.gray[500],
              hover: FOUNDATION_THEME.colors.gray[700],
              active: FOUNDATION_THEME.colors.gray[700],
              disabled: FOUNDATION_THEME.colors.gray[400],
            },
          },
          fontSize: {
            [TabsV2Size.SM]: FOUNDATION_THEME.font.size.body.md.fontSize,
            [TabsV2Size.MD]: FOUNDATION_THEME.font.size.body.md.fontSize,
            [TabsV2Size.LG]: FOUNDATION_THEME.font.size.body.md.fontSize,
          },
          fontWeight: {
            [TabsV2Size.SM]: FOUNDATION_THEME.font.weight[500],
            [TabsV2Size.MD]: FOUNDATION_THEME.font.weight[500],
            [TabsV2Size.LG]: FOUNDATION_THEME.font.weight[500],
          },
        },
        closeButton: {
          width: FOUNDATION_THEME.unit[16],
          borderRadius: FOUNDATION_THEME.border.radius.full,
          backgroundColor: {
            default: 'transparent',
            hover: FOUNDATION_THEME.colors.gray[100],
            active: FOUNDATION_THEME.colors.gray[150],
            disabled: 'transparent',
          },
        },
        transition: 'color 0.2s ease-in-out',
      },
    },
  },
}
