import { FOUNDATION_THEME, type ComponentTokenType } from '@juspay/blend-design-system'

/**
 * `TAGS` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/Tags/tag.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.TAGS ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const TAGS_TOKENS: NonNullable<ComponentTokenType['TAGS']> = {
  sm: {
    gap: FOUNDATION_THEME.unit[6],
    minWidth: 'fit-content',
    maxWidth: FOUNDATION_THEME.unit[200],
    width: 'fit-content',
    // Pattern: backgroundColor.[variant].[subType]
    // Example: backgroundColor.attentive.primary
    backgroundColor: {
      noFill: {
        neutral: FOUNDATION_THEME.colors.gray[0],
        primary: FOUNDATION_THEME.colors.gray[0],
        success: FOUNDATION_THEME.colors.gray[0],
        error: FOUNDATION_THEME.colors.gray[0],
        warning: FOUNDATION_THEME.colors.gray[0],
        purple: FOUNDATION_THEME.colors.gray[0],
      },
      attentive: {
        neutral: FOUNDATION_THEME.colors.gray[950],
        primary: FOUNDATION_THEME.colors.primary[600],
        success: FOUNDATION_THEME.colors.green[600],
        error: FOUNDATION_THEME.colors.red[600],
        warning: FOUNDATION_THEME.colors.orange[500],
        purple: FOUNDATION_THEME.colors.purple[500],
      },
      subtle: {
        neutral: FOUNDATION_THEME.colors.gray[50],
        primary: FOUNDATION_THEME.colors.primary[50],
        success: FOUNDATION_THEME.colors.green[50],
        error: FOUNDATION_THEME.colors.red[50],
        warning: FOUNDATION_THEME.colors.orange[50],
        purple: FOUNDATION_THEME.colors.purple[50],
      },
    },
    // Pattern: borderRadius.[size].[shape]
    // Example: borderRadius.lg.rounded
    borderRadius: {
      xs: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      sm: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      md: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      lg: {
        squarical: FOUNDATION_THEME.border.radius[8],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
    },
    // Pattern: padding.[size] (size-dependent)
    // Example: padding.lg
    padding: {
      xs: `${FOUNDATION_THEME.unit[2]} ${FOUNDATION_THEME.unit[6]}`,
      sm: `${FOUNDATION_THEME.unit[3]} ${FOUNDATION_THEME.unit[8]}`,
      md: `${FOUNDATION_THEME.unit[4]} ${FOUNDATION_THEME.unit[10]}`,
      lg: `${FOUNDATION_THEME.unit[6]} ${FOUNDATION_THEME.unit[12]}`,
    },
    // Pattern: border.[variant].[subType]
    // Example: border.noFill.primary
    border: {
      noFill: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[950]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[600]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[600]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
      subtle: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[100]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[100]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[100]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[100]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[100]}`,
      },
      attentive: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[950]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[600]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[600]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
    },
    // Pattern: height.[size] (size-dependent)
    // Example: height.md
    // height: {
    //     xs: FOUNDATION_THEME.unit[20],
    //     sm: FOUNDATION_THEME.unit[22],
    //     md: FOUNDATION_THEME.unit[24],
    //     lg: FOUNDATION_THEME.unit[28],
    // },
    text: {
      // Pattern: text.color.[variant].[subType]
      // Example: text.color.subtle.primary
      color: {
        noFill: {
          neutral: FOUNDATION_THEME.colors.gray[950],
          primary: FOUNDATION_THEME.colors.primary[800],
          success: FOUNDATION_THEME.colors.green[600],
          error: FOUNDATION_THEME.colors.red[600],
          warning: FOUNDATION_THEME.colors.orange[500],
          purple: FOUNDATION_THEME.colors.purple[500],
        },
        attentive: {
          neutral: FOUNDATION_THEME.colors.gray[0],
          primary: FOUNDATION_THEME.colors.gray[0],
          success: FOUNDATION_THEME.colors.gray[0],
          error: FOUNDATION_THEME.colors.gray[0],
          warning: FOUNDATION_THEME.colors.gray[0],
          purple: FOUNDATION_THEME.colors.gray[0],
        },
        subtle: {
          neutral: FOUNDATION_THEME.colors.gray[950],
          primary: FOUNDATION_THEME.colors.primary[600],
          success: FOUNDATION_THEME.colors.green[600],
          error: FOUNDATION_THEME.colors.red[600],
          warning: FOUNDATION_THEME.colors.orange[600],
          purple: FOUNDATION_THEME.colors.purple[600],
        },
      },
      // Pattern: text.fontSize.[size] (size-dependent)
      // Example: text.fontSize.md
      fontSize: {
        xs: FOUNDATION_THEME.font.size.body.sm.fontSize,
        sm: FOUNDATION_THEME.font.size.body.sm.fontSize,
        md: FOUNDATION_THEME.font.size.body.md.fontSize,
        lg: FOUNDATION_THEME.font.size.body.md.fontSize,
      },
      // Pattern: text.fontWeight.[size] (size-dependent)
      // Example: text.fontWeight.lg
      fontWeight: {
        xs: FOUNDATION_THEME.font.weight[500],
        sm: FOUNDATION_THEME.font.weight[500],
        md: FOUNDATION_THEME.font.weight[500],
        lg: FOUNDATION_THEME.font.weight[500],
      },
    },
  },
  lg: {
    gap: FOUNDATION_THEME.unit[6],
    minWidth: 'fit-content',
    maxWidth: FOUNDATION_THEME.unit[200],
    width: 'fit-content',
    // Pattern: backgroundColor.[variant].[subType]
    // Example: backgroundColor.attentive.primary
    backgroundColor: {
      noFill: {
        neutral: FOUNDATION_THEME.colors.gray[0],
        primary: FOUNDATION_THEME.colors.gray[0],
        success: FOUNDATION_THEME.colors.gray[0],
        error: FOUNDATION_THEME.colors.gray[0],
        warning: FOUNDATION_THEME.colors.gray[0],
        purple: FOUNDATION_THEME.colors.gray[0],
      },
      attentive: {
        neutral: FOUNDATION_THEME.colors.gray[950],
        primary: FOUNDATION_THEME.colors.primary[600],
        success: FOUNDATION_THEME.colors.green[600],
        error: FOUNDATION_THEME.colors.red[600],
        warning: FOUNDATION_THEME.colors.orange[500],
        purple: FOUNDATION_THEME.colors.purple[500],
      },
      subtle: {
        neutral: FOUNDATION_THEME.colors.gray[50],
        primary: FOUNDATION_THEME.colors.primary[50],
        success: FOUNDATION_THEME.colors.green[50],
        error: FOUNDATION_THEME.colors.red[50],
        warning: FOUNDATION_THEME.colors.orange[50],
        purple: FOUNDATION_THEME.colors.purple[50],
      },
    },
    // Pattern: borderRadius.[size].[shape]
    // Example: borderRadius.lg.rounded
    borderRadius: {
      xs: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      sm: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      md: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      lg: {
        squarical: FOUNDATION_THEME.border.radius[8],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
    },
    // Pattern: padding.[size] (size-dependent)
    // Example: padding.lg
    padding: {
      xs: `${FOUNDATION_THEME.unit[2]} ${FOUNDATION_THEME.unit[6]}`,
      sm: `${FOUNDATION_THEME.unit[3]} ${FOUNDATION_THEME.unit[8]}`,
      md: `${FOUNDATION_THEME.unit[4]} ${FOUNDATION_THEME.unit[10]}`,
      lg: `${FOUNDATION_THEME.unit[6]} ${FOUNDATION_THEME.unit[12]}`,
    },
    // Pattern: border.[variant].[subType]
    // Example: border.noFill.primary
    border: {
      noFill: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[950]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[600]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[600]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
      subtle: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[100]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[100]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[100]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[100]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[100]}`,
      },
      attentive: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[950]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[600]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[600]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
    },
    // Pattern: height.[size] (size-dependent)
    // Example: height.md
    // height: {
    //     xs: FOUNDATION_THEME.unit[20],
    //     sm: FOUNDATION_THEME.unit[22],
    //     md: FOUNDATION_THEME.unit[24],
    //     lg: FOUNDATION_THEME.unit[28],
    // },
    text: {
      // Pattern: text.color.[variant].[subType]
      // Example: text.color.subtle.primary
      color: {
        noFill: {
          neutral: FOUNDATION_THEME.colors.gray[950],
          primary: FOUNDATION_THEME.colors.primary[800],
          success: FOUNDATION_THEME.colors.green[600],
          error: FOUNDATION_THEME.colors.red[600],
          warning: FOUNDATION_THEME.colors.orange[500],
          purple: FOUNDATION_THEME.colors.purple[500],
        },
        attentive: {
          neutral: FOUNDATION_THEME.colors.gray[0],
          primary: FOUNDATION_THEME.colors.gray[0],
          success: FOUNDATION_THEME.colors.gray[0],
          error: FOUNDATION_THEME.colors.gray[0],
          warning: FOUNDATION_THEME.colors.gray[0],
          purple: FOUNDATION_THEME.colors.gray[0],
        },
        subtle: {
          neutral: FOUNDATION_THEME.colors.gray[950],
          primary: FOUNDATION_THEME.colors.primary[600],
          success: FOUNDATION_THEME.colors.green[600],
          error: FOUNDATION_THEME.colors.red[600],
          warning: FOUNDATION_THEME.colors.orange[600],
          purple: FOUNDATION_THEME.colors.purple[600],
        },
      },
      // Pattern: text.fontSize.[size] (size-dependent)
      // Example: text.fontSize.md
      fontSize: {
        xs: FOUNDATION_THEME.font.size.body.sm.fontSize,
        sm: FOUNDATION_THEME.font.size.body.sm.fontSize,
        md: FOUNDATION_THEME.font.size.body.md.fontSize,
        lg: FOUNDATION_THEME.font.size.body.md.fontSize,
      },
      // Pattern: text.fontWeight.[size] (size-dependent)
      // Example: text.fontWeight.lg
      fontWeight: {
        xs: FOUNDATION_THEME.font.weight[500],
        sm: FOUNDATION_THEME.font.weight[500],
        md: FOUNDATION_THEME.font.weight[500],
        lg: FOUNDATION_THEME.font.weight[500],
      },
    },
  },
}
