import { FOUNDATION_THEME, type ResponsiveTagV2Tokens } from '@juspay/blend-design-system'

/**
 * `TAGV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/TagV2/tagV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.TAGV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const TAGV2_TOKENS: ResponsiveTagV2Tokens = {
  sm: {
    gap: FOUNDATION_THEME.unit[6],
    backgroundColor: {
      noFill: {
        neutral: FOUNDATION_THEME.colors.gray[0],
        primary: FOUNDATION_THEME.colors.gray[0],
        success: FOUNDATION_THEME.colors.gray[0],
        error: FOUNDATION_THEME.colors.gray[0],
        warning: FOUNDATION_THEME.colors.gray[0],
        purple: FOUNDATION_THEME.colors.gray[0],
      },
      attentive: {
        neutral: FOUNDATION_THEME.colors.gray[950],
        primary: FOUNDATION_THEME.colors.primary[600],
        success: FOUNDATION_THEME.colors.green[600],
        error: FOUNDATION_THEME.colors.red[600],
        warning: FOUNDATION_THEME.colors.orange[500],
        purple: FOUNDATION_THEME.colors.purple[500],
      },
      subtle: {
        neutral: FOUNDATION_THEME.colors.gray[50],
        primary: FOUNDATION_THEME.colors.primary[50],
        success: FOUNDATION_THEME.colors.green[50],
        error: FOUNDATION_THEME.colors.red[50],
        warning: FOUNDATION_THEME.colors.orange[50],
        purple: FOUNDATION_THEME.colors.purple[50],
      },
    },

    borderRadius: {
      xs: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      sm: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      md: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      lg: {
        squarical: FOUNDATION_THEME.border.radius[8],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
    },

    height: {
      xs: `${FOUNDATION_THEME.unit[20]}`,
      sm: `${FOUNDATION_THEME.unit[22]}`,
      md: `${FOUNDATION_THEME.unit[24]}`,
      lg: `${FOUNDATION_THEME.unit[28]}`,
    },

    padding: {
      top: {
        xs: `${FOUNDATION_THEME.unit[2]}`,
        sm: `${FOUNDATION_THEME.unit[3]}`,
        md: `${FOUNDATION_THEME.unit[4]}`,
        lg: `${FOUNDATION_THEME.unit[6]}`,
      },
      right: {
        xs: `${FOUNDATION_THEME.unit[6]}`,
        sm: `${FOUNDATION_THEME.unit[8]}`,
        md: `${FOUNDATION_THEME.unit[10]}`,
        lg: `${FOUNDATION_THEME.unit[12]}`,
      },
      bottom: {
        xs: `${FOUNDATION_THEME.unit[2]}`,
        sm: `${FOUNDATION_THEME.unit[3]}`,
        md: `${FOUNDATION_THEME.unit[4]}`,
        lg: `${FOUNDATION_THEME.unit[6]}`,
      },
      left: {
        xs: `${FOUNDATION_THEME.unit[6]}`,
        sm: `${FOUNDATION_THEME.unit[8]}`,
        md: `${FOUNDATION_THEME.unit[10]}`,
        lg: `${FOUNDATION_THEME.unit[12]}`,
      },
    },

    border: {
      noFill: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[950]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[600]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[600]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
      subtle: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[100]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[100]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[100]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[100]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[100]}`,
      },
      attentive: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[950]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[600]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[600]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
    },
    leftSlot: {
      maxHeight: {
        xs: `${FOUNDATION_THEME.unit[12]}`,
        sm: `${FOUNDATION_THEME.unit[12]}`,
        md: `${FOUNDATION_THEME.unit[12]}`,
        lg: `${FOUNDATION_THEME.unit[12]}`,
      },
    },
    rightSlot: {
      maxHeight: {
        xs: `${FOUNDATION_THEME.unit[12]}`,
        sm: `${FOUNDATION_THEME.unit[12]}`,
        md: `${FOUNDATION_THEME.unit[12]}`,
        lg: `${FOUNDATION_THEME.unit[12]}`,
      },
    },
    text: {
      color: {
        noFill: {
          neutral: FOUNDATION_THEME.colors.gray[950],
          primary: FOUNDATION_THEME.colors.primary[800],
          success: FOUNDATION_THEME.colors.green[600],
          error: FOUNDATION_THEME.colors.red[600],
          warning: FOUNDATION_THEME.colors.orange[500],
          purple: FOUNDATION_THEME.colors.purple[500],
        },
        attentive: {
          neutral: FOUNDATION_THEME.colors.gray[0],
          primary: FOUNDATION_THEME.colors.gray[0],
          success: FOUNDATION_THEME.colors.gray[0],
          error: FOUNDATION_THEME.colors.gray[0],
          warning: FOUNDATION_THEME.colors.gray[0],
          purple: FOUNDATION_THEME.colors.gray[0],
        },
        subtle: {
          neutral: FOUNDATION_THEME.colors.gray[950],
          primary: FOUNDATION_THEME.colors.primary[600],
          success: FOUNDATION_THEME.colors.green[600],
          error: FOUNDATION_THEME.colors.red[600],
          warning: FOUNDATION_THEME.colors.orange[600],
          purple: FOUNDATION_THEME.colors.purple[600],
        },
      },

      fontSize: {
        xs: FOUNDATION_THEME.font.fontSize[12],
        sm: FOUNDATION_THEME.font.fontSize[12],
        md: FOUNDATION_THEME.font.fontSize[14],
        lg: FOUNDATION_THEME.font.fontSize[14],
      },

      fontWeight: {
        xs: FOUNDATION_THEME.font.weight[500],
        sm: FOUNDATION_THEME.font.weight[500],
        md: FOUNDATION_THEME.font.weight[500],
        lg: FOUNDATION_THEME.font.weight[500],
      },
      lineHeight: {
        xs: FOUNDATION_THEME.font.lineHeight[18],
        sm: FOUNDATION_THEME.font.lineHeight[18],
        md: FOUNDATION_THEME.font.lineHeight[20],
        lg: FOUNDATION_THEME.font.lineHeight[20],
      },
    },
  },
  lg: {
    gap: FOUNDATION_THEME.unit[6],
    backgroundColor: {
      noFill: {
        neutral: FOUNDATION_THEME.colors.gray[0],
        primary: FOUNDATION_THEME.colors.gray[0],
        success: FOUNDATION_THEME.colors.gray[0],
        error: FOUNDATION_THEME.colors.gray[0],
        warning: FOUNDATION_THEME.colors.gray[0],
        purple: FOUNDATION_THEME.colors.gray[0],
      },
      attentive: {
        neutral: FOUNDATION_THEME.colors.gray[950],
        primary: FOUNDATION_THEME.colors.primary[600],
        success: FOUNDATION_THEME.colors.green[600],
        error: FOUNDATION_THEME.colors.red[600],
        warning: FOUNDATION_THEME.colors.orange[500],
        purple: FOUNDATION_THEME.colors.purple[500],
      },
      subtle: {
        neutral: FOUNDATION_THEME.colors.gray[50],
        primary: FOUNDATION_THEME.colors.primary[50],
        success: FOUNDATION_THEME.colors.green[50],
        error: FOUNDATION_THEME.colors.red[50],
        warning: FOUNDATION_THEME.colors.orange[50],
        purple: FOUNDATION_THEME.colors.purple[50],
      },
    },

    borderRadius: {
      xs: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      sm: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      md: {
        squarical: FOUNDATION_THEME.border.radius[6],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
      lg: {
        squarical: FOUNDATION_THEME.border.radius[8],
        rounded: FOUNDATION_THEME.border.radius.full,
      },
    },
    height: {
      xs: `${FOUNDATION_THEME.unit[20]}`,
      sm: `${FOUNDATION_THEME.unit[22]}`,
      md: `${FOUNDATION_THEME.unit[24]}`,
      lg: `${FOUNDATION_THEME.unit[28]}`,
    },
    padding: {
      top: {
        xs: `${FOUNDATION_THEME.unit[2]} `,
        sm: `${FOUNDATION_THEME.unit[3]} `,
        md: `${FOUNDATION_THEME.unit[4]} `,
        lg: `${FOUNDATION_THEME.unit[6]} `,
      },
      right: {
        xs: `${FOUNDATION_THEME.unit[6]}`,
        sm: ` ${FOUNDATION_THEME.unit[8]}`,
        md: `${FOUNDATION_THEME.unit[10]}`,
        lg: `${FOUNDATION_THEME.unit[12]}`,
      },
      bottom: {
        xs: `${FOUNDATION_THEME.unit[2]} `,
        sm: `${FOUNDATION_THEME.unit[3]} `,
        md: `${FOUNDATION_THEME.unit[4]} `,
        lg: `${FOUNDATION_THEME.unit[6]} `,
      },
      left: {
        xs: ` ${FOUNDATION_THEME.unit[6]}`,
        sm: ` ${FOUNDATION_THEME.unit[8]}`,
        md: ` ${FOUNDATION_THEME.unit[10]}`,
        lg: ` ${FOUNDATION_THEME.unit[12]}`,
      },
    },
    border: {
      noFill: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[950]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[600]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[600]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
      subtle: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[100]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[100]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[100]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[100]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[100]}`,
      },
      attentive: {
        neutral: `1px solid ${FOUNDATION_THEME.colors.gray[950]}`,
        primary: `1px solid ${FOUNDATION_THEME.colors.primary[600]}`,
        success: `1px solid ${FOUNDATION_THEME.colors.green[600]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[600]}`,
        warning: `1px solid ${FOUNDATION_THEME.colors.orange[500]}`,
        purple: `1px solid ${FOUNDATION_THEME.colors.purple[500]}`,
      },
    },
    leftSlot: {
      maxHeight: {
        xs: `${FOUNDATION_THEME.unit[12]}`,
        sm: `${FOUNDATION_THEME.unit[12]}`,
        md: `${FOUNDATION_THEME.unit[12]}`,
        lg: `${FOUNDATION_THEME.unit[12]}`,
      },
    },
    rightSlot: {
      maxHeight: {
        xs: `${FOUNDATION_THEME.unit[12]}`,
        sm: `${FOUNDATION_THEME.unit[12]}`,
        md: `${FOUNDATION_THEME.unit[12]}`,
        lg: `${FOUNDATION_THEME.unit[12]}`,
      },
    },
    text: {
      color: {
        noFill: {
          neutral: FOUNDATION_THEME.colors.gray[950],
          primary: FOUNDATION_THEME.colors.primary[800],
          success: FOUNDATION_THEME.colors.green[600],
          error: FOUNDATION_THEME.colors.red[600],
          warning: FOUNDATION_THEME.colors.orange[500],
          purple: FOUNDATION_THEME.colors.purple[500],
        },
        attentive: {
          neutral: FOUNDATION_THEME.colors.gray[0],
          primary: FOUNDATION_THEME.colors.gray[0],
          success: FOUNDATION_THEME.colors.gray[0],
          error: FOUNDATION_THEME.colors.gray[0],
          warning: FOUNDATION_THEME.colors.gray[0],
          purple: FOUNDATION_THEME.colors.gray[0],
        },
        subtle: {
          neutral: FOUNDATION_THEME.colors.gray[950],
          primary: FOUNDATION_THEME.colors.primary[600],
          success: FOUNDATION_THEME.colors.green[600],
          error: FOUNDATION_THEME.colors.red[600],
          warning: FOUNDATION_THEME.colors.orange[600],
          purple: FOUNDATION_THEME.colors.purple[600],
        },
      },

      fontSize: {
        xs: FOUNDATION_THEME.font.fontSize[12],
        sm: FOUNDATION_THEME.font.fontSize[12],
        md: FOUNDATION_THEME.font.fontSize[14],
        lg: FOUNDATION_THEME.font.fontSize[14],
      },

      fontWeight: {
        xs: FOUNDATION_THEME.font.weight[500],
        sm: FOUNDATION_THEME.font.weight[500],
        md: FOUNDATION_THEME.font.weight[500],
        lg: FOUNDATION_THEME.font.weight[500],
      },
      lineHeight: {
        xs: FOUNDATION_THEME.font.lineHeight[18],
        sm: FOUNDATION_THEME.font.lineHeight[18],
        md: FOUNDATION_THEME.font.lineHeight[20],
        lg: FOUNDATION_THEME.font.lineHeight[20],
      },
    },
  },
}
