import { FOUNDATION_THEME, type ResponsiveTextInputV2Tokens } from '@juspay/blend-design-system'

/**
 * `TEXT_INPUTV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/InputsV2/TextInputV2/TextInputV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.TEXT_INPUTV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const TEXT_INPUTV2_TOKENS: ResponsiveTextInputV2Tokens = {
  sm: {
    gap: FOUNDATION_THEME.unit[8],
    topContainer: {
      label: {
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[700],
          hover: FOUNDATION_THEME.colors.gray[700],
          focus: FOUNDATION_THEME.colors.gray[700],
          disabled: FOUNDATION_THEME.colors.gray[400],
          error: FOUNDATION_THEME.colors.red[600],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
      },
      subLabel: {
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[400],
          md: FOUNDATION_THEME.font.weight[400],
          lg: FOUNDATION_THEME.font.weight[400],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[300],
          error: FOUNDATION_THEME.colors.red[600],
        },
      },
      helpIcon: {
        width: {
          sm: FOUNDATION_THEME.unit[14],
          md: FOUNDATION_THEME.unit[14],
          lg: FOUNDATION_THEME.unit[14],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[400],
          error: FOUNDATION_THEME.colors.red[600],
        },
      },
      required: {
        color: FOUNDATION_THEME.colors.red[600],
      },
    },
    inputContainer: {
      gap: FOUNDATION_THEME.unit[8],
      placeholder: {
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[400],
          error: FOUNDATION_THEME.colors.red[600],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
      },
      inputText: {
        fontSize: {
          sm: FOUNDATION_THEME.font.size.body.md.fontSize,
          md: FOUNDATION_THEME.font.size.body.md.fontSize,
          lg: FOUNDATION_THEME.font.size.body.md.fontSize,
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[18],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[700],
          hover: FOUNDATION_THEME.colors.gray[700],
          focus: FOUNDATION_THEME.colors.gray[700],
          error: FOUNDATION_THEME.colors.red[800],
          disabled: FOUNDATION_THEME.colors.gray[300],
        },
      },
      borderRadius: {
        sm: FOUNDATION_THEME.unit[10],
        md: FOUNDATION_THEME.unit[10],
        lg: FOUNDATION_THEME.unit[10],
      },
      padding: {
        top: {
          sm: FOUNDATION_THEME.unit[6],
          md: FOUNDATION_THEME.unit[7],
          lg: FOUNDATION_THEME.unit[15],
        },
        right: {
          sm: FOUNDATION_THEME.unit[12],
          md: FOUNDATION_THEME.unit[12],
          lg: FOUNDATION_THEME.unit[12],
        },
        bottom: {
          sm: FOUNDATION_THEME.unit[6],
          md: FOUNDATION_THEME.unit[7],
          lg: FOUNDATION_THEME.unit[15],
        },
        left: {
          sm: FOUNDATION_THEME.unit[12],
          md: FOUNDATION_THEME.unit[12],
          lg: FOUNDATION_THEME.unit[12],
        },
      },
      border: {
        default: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        hover: `1px solid ${FOUNDATION_THEME.colors.gray[400]}`,
        focus: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        disabled: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      },
      backgroundColor: {
        default: FOUNDATION_THEME.colors.gray[0],
        disabled: FOUNDATION_THEME.colors.gray[50],
        hover: FOUNDATION_THEME.colors.gray[0],
        focus: FOUNDATION_THEME.colors.gray[0],
        error: FOUNDATION_THEME.colors.gray[0],
      },
      boxShadow: FOUNDATION_THEME.shadows.sm,
    },
    bottomContainer: {
      hintText: {
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[400],
          md: FOUNDATION_THEME.font.weight[400],
          lg: FOUNDATION_THEME.font.weight[400],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[500],
          hover: FOUNDATION_THEME.colors.gray[500],
          focus: FOUNDATION_THEME.colors.gray[500],
          disabled: FOUNDATION_THEME.colors.gray[400],
          error: FOUNDATION_THEME.colors.red[600],
        },
      },
      errorMessage: {
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: FOUNDATION_THEME.colors.red[600],
      },
    },
  },
  lg: {
    gap: FOUNDATION_THEME.unit[8],
    topContainer: {
      label: {
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[700],
          hover: FOUNDATION_THEME.colors.gray[700],
          focus: FOUNDATION_THEME.colors.gray[700],
          disabled: FOUNDATION_THEME.colors.gray[400],
          error: FOUNDATION_THEME.colors.red[600],
        },
      },
      subLabel: {
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[400],
          md: FOUNDATION_THEME.font.weight[400],
          lg: FOUNDATION_THEME.font.weight[400],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[300],
          error: FOUNDATION_THEME.colors.red[600],
        },
      },
      helpIcon: {
        width: {
          sm: FOUNDATION_THEME.unit[14],
          md: FOUNDATION_THEME.unit[14],
          lg: FOUNDATION_THEME.unit[14],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[400],
          error: FOUNDATION_THEME.colors.red[600],
        },
      },
      required: {
        color: FOUNDATION_THEME.colors.red[600],
      },
    },
    inputContainer: {
      gap: FOUNDATION_THEME.unit[8],
      placeholder: {
        color: {
          default: FOUNDATION_THEME.colors.gray[400],
          hover: FOUNDATION_THEME.colors.gray[400],
          focus: FOUNDATION_THEME.colors.gray[400],
          disabled: FOUNDATION_THEME.colors.gray[400],
          error: FOUNDATION_THEME.colors.red[600],
        },
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
      },
      inputText: {
        fontSize: {
          sm: FOUNDATION_THEME.font.size.body.md.fontSize,
          md: FOUNDATION_THEME.font.size.body.md.fontSize,
          lg: FOUNDATION_THEME.font.size.body.md.fontSize,
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[18],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[700],
          hover: FOUNDATION_THEME.colors.gray[700],
          focus: FOUNDATION_THEME.colors.gray[700],
          error: FOUNDATION_THEME.colors.red[800],
          disabled: FOUNDATION_THEME.colors.gray[300],
        },
      },
      borderRadius: {
        sm: FOUNDATION_THEME.unit[10],
        md: FOUNDATION_THEME.unit[10],
        lg: FOUNDATION_THEME.unit[10],
      },
      padding: {
        top: {
          sm: FOUNDATION_THEME.unit[6],
          md: FOUNDATION_THEME.unit[7],
          lg: FOUNDATION_THEME.unit[9],
        },
        right: {
          sm: FOUNDATION_THEME.unit[12],
          md: FOUNDATION_THEME.unit[12],
          lg: FOUNDATION_THEME.unit[14],
        },
        bottom: {
          sm: FOUNDATION_THEME.unit[6],
          md: FOUNDATION_THEME.unit[7],
          lg: FOUNDATION_THEME.unit[9],
        },
        left: {
          sm: FOUNDATION_THEME.unit[12],
          md: FOUNDATION_THEME.unit[12],
          lg: FOUNDATION_THEME.unit[14],
        },
      },
      border: {
        default: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
        hover: `1px solid ${FOUNDATION_THEME.colors.gray[400]}`,
        focus: `1px solid ${FOUNDATION_THEME.colors.primary[500]}`,
        error: `1px solid ${FOUNDATION_THEME.colors.red[500]}`,
        disabled: `1px solid ${FOUNDATION_THEME.colors.gray[200]}`,
      },
      backgroundColor: {
        default: FOUNDATION_THEME.colors.gray[0],
        disabled: FOUNDATION_THEME.colors.gray[50],
        hover: FOUNDATION_THEME.colors.gray[0],
        focus: FOUNDATION_THEME.colors.gray[0],
        error: FOUNDATION_THEME.colors.gray[0],
      },
      boxShadow: FOUNDATION_THEME.shadows.sm,
    },
    bottomContainer: {
      hintText: {
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[400],
          md: FOUNDATION_THEME.font.weight[400],
          lg: FOUNDATION_THEME.font.weight[400],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: {
          default: FOUNDATION_THEME.colors.gray[500],
          hover: FOUNDATION_THEME.colors.gray[500],
          focus: FOUNDATION_THEME.colors.gray[500],
          disabled: FOUNDATION_THEME.colors.gray[400],
          error: FOUNDATION_THEME.colors.red[600],
        },
      },
      errorMessage: {
        fontSize: {
          sm: FOUNDATION_THEME.font.fontSize[14],
          md: FOUNDATION_THEME.font.fontSize[14],
          lg: FOUNDATION_THEME.font.fontSize[14],
        },
        fontWeight: {
          sm: FOUNDATION_THEME.font.weight[500],
          md: FOUNDATION_THEME.font.weight[500],
          lg: FOUNDATION_THEME.font.weight[500],
        },
        lineHeight: {
          sm: FOUNDATION_THEME.font.lineHeight[20],
          md: FOUNDATION_THEME.font.lineHeight[20],
          lg: FOUNDATION_THEME.font.lineHeight[20],
        },
        color: FOUNDATION_THEME.colors.red[600],
      },
    },
  },
}
