import { FOUNDATION_THEME, type ResponsiveTopbarV2Tokens } from '@juspay/blend-design-system'

/**
 * `TOPBARV2` — the complete token tree for this component, at the values 0.0.37 ships.
 *
 * GENERATED by scripts/gen-tokens.mjs from lib/components/TopbarV2/topbarV2.light.tokens.ts. Edit a value
 * in place to override it; `npm run tokens:check` then reports the difference against the
 * installed default — which is the point. An intentional override shows up, and so does a
 * Blend upgrade that moves a default nobody touched.
 *
 * The whole tree is here because overrides REPLACE rather than merge: initComponentTokens
 * resolves every slot as `componentTokens.TOPBARV2 ?? get…(…)`, so a partial object
 * discards everything it does not mention. Never prune paths.
 *
 * ⚠️ Light values. Handing this to ThemeProvider replaces the dark defaults too, so it
 * pins the component to light until a dark tree is generated beside it.
 */
export const TOPBARV2_TOKENS: ResponsiveTopbarV2Tokens = {
  sm: {
    zIndex: '10',
    height: FOUNDATION_THEME.unit[48],
    borderBottom: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
    backgroundColor: 'hsla(0, 0%, 100%, 0.8)',
    backdropFilter: 'blur(10px)',
    padding: `${FOUNDATION_THEME.unit[5]} ${FOUNDATION_THEME.unit[16]}`,
    gap: FOUNDATION_THEME.unit[12],
    separator: {
      width: '1.5px',
      color: FOUNDATION_THEME.colors.gray[200],
    },
    toggleButton: {
      borderRadius: FOUNDATION_THEME.border.radius[10],
      padding: FOUNDATION_THEME.unit[9],
      backgroundColor: {
        default: 'transparent',
        hover: FOUNDATION_THEME.colors.gray[100],
        active: FOUNDATION_THEME.colors.gray[150],
      },
      transition: 'background-color 0.15s ease',
      icon: {
        size: FOUNDATION_THEME.unit[16],
        color: FOUNDATION_THEME.colors.gray[600],
      },
    },
    actionButton: {
      borderRadius: FOUNDATION_THEME.border.radius[8],
      padding: FOUNDATION_THEME.unit[8],
      minWidth: FOUNDATION_THEME.unit[40],
      height: FOUNDATION_THEME.unit[40],
      backgroundColor: {
        default: 'transparent',
        hover: FOUNDATION_THEME.colors.gray[100],
        active: FOUNDATION_THEME.colors.gray[150],
      },
      transition: 'background-color 0.15s ease',
      icon: {
        size: FOUNDATION_THEME.unit[20],
        color: FOUNDATION_THEME.colors.gray[600],
      },
    },
    tenantIconButton: {
      borderRadius: FOUNDATION_THEME.border.radius[8],
      minHeight: FOUNDATION_THEME.unit[36],
      backgroundColor: {
        default: 'transparent',
        hover: FOUNDATION_THEME.colors.gray[100],
        active: FOUNDATION_THEME.colors.gray[150],
      },
      transition: 'background-color 0.15s ease',
    },
    merchantSelectTrigger: {
      gap: FOUNDATION_THEME.unit[6],
      icon: {
        size: FOUNDATION_THEME.unit[14],
        color: FOUNDATION_THEME.colors.gray[600],
      },
      text: {
        fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[600],
        color: FOUNDATION_THEME.colors.gray[800],
      },
    },
    leftSection: {
      gap: FOUNDATION_THEME.unit[6],
      maxHeight: '26px',
      divider: {
        fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[400],
        color: FOUNDATION_THEME.colors.gray[400],
      },
    },
    rightSection: { gap: FOUNDATION_THEME.unit[8] },
    sidebarSection: { gap: FOUNDATION_THEME.unit[16] },
  },
  lg: {
    zIndex: '10',
    height: FOUNDATION_THEME.unit[48],
    borderBottom: `${FOUNDATION_THEME.border.width[1]} solid ${FOUNDATION_THEME.colors.gray[200]}`,
    backgroundColor: 'hsla(0, 0%, 100%, 0.8)',
    backdropFilter: 'blur(10px)',
    padding: `${FOUNDATION_THEME.unit[5]} ${FOUNDATION_THEME.unit[32]}`,
    gap: FOUNDATION_THEME.unit[16],
    separator: {
      width: '1.5px',
      color: FOUNDATION_THEME.colors.gray[200],
    },
    toggleButton: {
      borderRadius: FOUNDATION_THEME.border.radius[10],
      padding: FOUNDATION_THEME.unit[10],
      backgroundColor: {
        default: 'transparent',
        hover: FOUNDATION_THEME.colors.gray[100],
        active: FOUNDATION_THEME.colors.gray[150],
      },
      transition: 'background-color 0.15s ease',
      icon: {
        size: FOUNDATION_THEME.unit[16],
        color: FOUNDATION_THEME.colors.gray[600],
      },
    },
    actionButton: {
      borderRadius: FOUNDATION_THEME.border.radius[8],
      padding: FOUNDATION_THEME.unit[8],
      minWidth: FOUNDATION_THEME.unit[40],
      height: FOUNDATION_THEME.unit[36],
      backgroundColor: {
        default: 'transparent',
        hover: FOUNDATION_THEME.colors.gray[100],
        active: FOUNDATION_THEME.colors.gray[150],
      },
      transition: 'background-color 0.15s ease',
      icon: {
        size: FOUNDATION_THEME.unit[20],
        color: FOUNDATION_THEME.colors.gray[600],
      },
    },
    tenantIconButton: {
      borderRadius: FOUNDATION_THEME.border.radius[8],
      minHeight: FOUNDATION_THEME.unit[36],
      backgroundColor: {
        default: 'transparent',
        hover: FOUNDATION_THEME.colors.gray[100],
        active: FOUNDATION_THEME.colors.gray[150],
      },
      transition: 'background-color 0.15s ease',
    },
    merchantSelectTrigger: {
      gap: FOUNDATION_THEME.unit[6],
      icon: {
        size: FOUNDATION_THEME.unit[14],
        color: FOUNDATION_THEME.colors.gray[600],
      },
      text: {
        fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[600],
        color: FOUNDATION_THEME.colors.gray[800],
      },
    },
    leftSection: {
      gap: FOUNDATION_THEME.unit[6],
      maxHeight: '26px',
      divider: {
        fontSize: FOUNDATION_THEME.font.size.body.md.fontSize,
        fontWeight: FOUNDATION_THEME.font.weight[400],
        color: FOUNDATION_THEME.colors.gray[400],
      },
    },
    rightSection: { gap: FOUNDATION_THEME.unit[8] },
    sidebarSection: { gap: FOUNDATION_THEME.unit[16] },
  },
}
